### ISSUE TITLE
Proposal: Adding ESLint Plugin for JSDoc

### ISSUE THREAD

**Issue by mass2527** [toss/es-toolkit#105]
I think it would be great if we add the ESLint plugin for JSDoc.

By using [`eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc), we can easily find mistakes with minimal effort. For example, if a template is missing, it will notify us about that.

<img width="1168" alt="Screenshot 2024-07-01 at 9:44:47 PM" src="https://github.com/toss/es-toolkit/assets/70563791/fabb46c7-70af-461a-ab41-f384c94420dc">

In addition to this, it will notify us if we don't use @param or @returns, and it will also let us know if the parameter names don't match the ones used in the function.

I would like to know your opinion on this.

**Comment by raon0211** [comment]
Adding this would be very helpful.

**Comment by mass2527** [comment]
I am going to make PR for this.
