### ISSUE TITLE
Support for `forEachRight`

### ISSUE THREAD

**Issue by haejunejung** [toss/es-toolkit#107]
Hello, 
If you need [loadsh's forEachRight](https://lodash.com/docs/4.17.15#forEachRight) function, Can I work it?

If it is okay to proceed, lodash's forEachRight supports both Array and Object, but in [#91], I would like to ask if it is only necessary to implement array in the array category.

**Comment by raon0211** [comment]
Sure! I think we might just implement it for arrays.

**Comment by haejunejung** [comment]
I've implemented a forEachRight function:

```ts
export function forEachRight<T>(arr: T[] = [], callbackfn: (value: T, index: number, arr: T[]) => void): void {
  for (let i = arr.length - 1; i >= 0; i--) {
    const element = arr[i];
    callbackfn(element, i, arr);
  }
}
```

If this implementation looks good, may I proceed with enhancing the documentation and tests, and then submit a pull request?

**Comment by haejunejung** [comment]
Oh, I think the code you suggested is better too. 
Thanks for your help 👍
