### ISSUE TITLE
Why don't we use Vitest globals?

### ISSUE THREAD

**Issue by po4tion** [toss/es-toolkit#111]
Vitest provides a convenient testing environment. One of them, the "globals" option, provides auto import functionality.

With this feature, We will no longer need to "import" repeatedly when writing test codes.

You can refer to it [here](https://vitest.dev/config/#globals).
You can refer to the global API provided through the "globals" option in [this link](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/constants.ts#L33).

If you accept this issue positively, I would like to work on it.

**Comment by raon0211** [comment]
Personally, I believe where the functions are imported from should be explicit. I thought that using global functions is a legacy of Jest.

For example, we have to [explicitly import `describe` and `it`](https://nodejs.org/api/test.html) when using the `node:test` module in Node.js.

It is similar in [Deno](https://docs.deno.com/runtime/manual/basics/testing/behavior_driven_development/) where we have to either explicitly use `Deno.test(...)` or import `describe` and `it` from [@std/testing](https://jsr.io/@std/testing).

**Comment by po4tion** [comment]
I understand, and it makes sense that the use of global functions may be less obvious than explicitly importing functions from the code.

In particular, the explicit "import" approach clearly reveals the dependence of the code, which can be useful for new developers or developers doing maintenance.

Thank you for your answer!
