### ISSUE TITLE
Support for `invert`

### ISSUE THREAD

**Issue by wondonghwi** [toss/es-toolkit#116]
hello!
If you need [lodash's invert](https://lodash.com/docs/4.17.15#invert) function,

Can I work on it?

I've given this a try:
```typescript
type InvertObject = { [key: string]: string };

export function invert<T extends Record<string, any>>(obj: T): InvertObject {
  const result: InvertObject = {};

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    result[value] = key;
  }

  return result;
}
```
The reason for using the any type in this code is to ensure flexibility. The invert function is designed to work with objects that can have values of any type.

If the above code looks good, may I proceed with enhancing the documentation and tests, and then submit a pull request?

**Comment by raon0211** [comment]
The implementation looks good to me, except we might slightly improve the type here.

```tsx
export function invert<K extends string | number | symbol, V extends string | number | symbol>(obj: Record<K, V>): { [key in V]: K } {
  const result = {} as { [key in V]: K };

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    result[value] = key;
  }

  return result;
}
```

**Comment by wondonghwi** [comment]
@raon0211 

Thank you, I will work on it as you advised and write the test code and document and upload the pull-request.

Thanks to you, I learned something new. Thank you!
