### ISSUE TITLE
Support for `snakeCase`

### ISSUE THREAD

**Issue by haejunejung** [toss/es-toolkit#120]
Hello, @raon0211 !
if you need [lodash's snakeCase](https://lodash.com/docs/4.17.15#snakeCase) function, Can I work `snakeCase` of #91 ?

**Comment by raon0211** [comment]
Sure!

**Comment by haejunejung** [comment]
I've implemented a`snakeCase` function as below:

```ts
export const snakeCase = (str: string): string => {
  const splitWords = str.match(/[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g) || [];
  return splitWords.map(word => word.toLowerCase()).join('_');
};

```

![image](https://github.com/toss/es-toolkit/assets/99087502/c50144eb-e088-4662-b075-53ae6075b986)
![image](https://github.com/toss/es-toolkit/assets/99087502/39fd5df9-3961-4a7e-89f4-6f37119d9b6d)


when I did several tests, it is fine. If this implementation looks good, I proceed with enhancing the documentation and test, and then submit a pull request.

One additional question is that the deployment environment for string is not ready. Should I proceed with this part included?

![image](https://github.com/toss/es-toolkit/assets/99087502/94646897-8366-4f57-b160-3a210e1e17c4)

**Comment by raon0211** [comment]
The implementation looks good, but we might make the RegExp to a constant in some directory like `constants`. It will help implement other string functions.

Additionally, I think we might add a new `exports` field, `"./string"`.

**Comment by haejunejung** [comment]
Thank you for your comment 👍
I was having trouble while implementing after hearing the comments. I would like to read it and get some advice on which method would be better.

In the cases that are currently being provided by string (ex. kabab, snake, camel..), I think the necessary regex is the reCasePattern below.

```ts

// The follwing regex pattern, reCasePattern, is designed to handle various case formats,
// found in string inputs (e.g., kabab, snake, camel)
const reCasePattern = /[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g
```

reCasePattern can classify several cases when implementing it. I think it can be categorized into 4 categories.

```ts
// 1. Matches sequences of two or more consecutive uppercase letters
const reUppercaseWord = /[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)/;

// 2. Matches mixed-case words or words starting with an optional uppercase letter,
// follwed by lowercase letters and optional digits
const reMixedcaseWord = /[A-Z]?[a-z]+[0-9]*/;

// 3. Matches single uppercase letters
const reUppercaseLetter = /[A-Z]/;

// 4. Matches sequences of digis
const reDigits = /[0-9]+/;
```

Below are two ways to implement this. I would like to get advice on which method is better.

### First Case: Partition and Combine Programmatically
```ts
// first case: partition the regex patterns and combine them programmatically.
const reUppercaseWord = /[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)/;
const reMixedcaseWord = /[A-Z]?[a-z]+[0-9]*/;
const reUppercaseLetter = /[A-Z]/;
const reDigits = /[0-9]+/;
 const reCasePattern = new RegExp(`${reUppercaseWord.source}|${reMixedcaseWord.source}|${reUppercaseLetter.source}|${reDigits.source}`,'g');
```

There is a way to separate them and combine them programmatically. At this time, the method is to separate several patterns in files such as constants/regex and utilize them. If implemented this way, I would like to ask whether each pattern needs to be separated into files.

### Second Case: Direct Use of Combined reCasePattern
```ts
// second case: directly use the combined reCasePattern
const reCasePattern = /[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g;
```

Alternatively, is it sufficient to maintain reCasePattern as a single entity without splitting into separate files for each pattern?

**Comment by raon0211** [comment]
Oh, sorry for the late reply. I guess the first case is much more readable. We might fix the current implementation.

Closing the issue since `snakeCase` was implemented.
