### ISSUE TITLE
Why do we need postbuild.sh?

### ISSUE THREAD

**Issue by po4tion** [toss/es-toolkit#121]
I have a question. Why do we need this file([.scripts/postbuild.sh](https://github.com/toss/es-toolkit/blob/main/.scripts/postbuild.sh))?

_Originally posted by @po4tion in https://github.com/toss/es-toolkit/issues/16#issuecomment-2205074067_

**Comment by manudeli** [comment]
👀 (I'm curious about this too)

**Comment by raon0211** [comment]
Without this, TypeScript cannot resolve the types correctly when we use `"moduleResolution": "Node10"`, the default resolution method. This happens because it does not respect the `exports` field.

You can verify this with [Are the types wrong?](https://arethetypeswrong.github.io/).

**Comment by manudeli** [comment]
@raon0211 When I remove postbuild.sh, I could see below error(Resolution failed). I understood it

<img width="1384" alt="image" src="https://github.com/toss/es-toolkit/assets/61593290/40a0cc29-64eb-4e37-8ea9-7cc34d0e676a">

@po4tion You can test like below
1. remove `./.scripts/postbuild.sh` in build script of package.json
    ```diff
    - "build": "tsup && ./.scripts/postbuild.sh",
    + "build": "tsup",
    ``` 
2. yarn pack to make package.tgz
3. put package.tgz in file input of [Are the types wrong?](https://arethetypeswrong.github.io/)
4. You can see this error

**Comment by po4tion** [comment]
Thanks to you, I solved my curiosity
