### ISSUE TITLE
Support for `deepFlatThenMap`

### ISSUE THREAD

**Issue by ssi02014** [toss/es-toolkit#122]
👋 Hi!

I'd like to propose a completely new function that doesn't exist in `lodash`. 🙏

The `deepFlatThenMap` function I'm proposing doesn't do the flattening after the `map` call, like `lodash's flatMapDeep(map().flat())`. 

It's a function that flattens an array of all depths, and then applies a callback function to each element.

Below is the code I'm considering  

### Interface
```ts
/**
 * Utility type for recursively unpacking nested array types to extract the type of the innermost element 
 * 
 * ExtractNestedArrayType<(number | (number | number[])[])[]> // number
 * ExtractNestedArrayType<(boolean | (string | number[])[])[]>; // string | number | boolean
 */
type ExtractNestedArrayType<T> = T extends readonly (infer U)[] ? ExtractNestedArrayType<U> : T;

/**
 * @example deepFlatThenMap([1, 2, [3, 4, [5, 6]]])
 */
export function deepFlatThenMap<T>(
  arr: readonly T[]
): ExtractNestedArrayType<T>[];

/**
 * @example deepFlatThenMap([1, 2, [3, 4, [5, 6]]], (item) => ({ id: item }))
 */
export function deepFlatThenMap<T, U>(
  arr: readonly T[],
  iteratee: (item: ExtractNestedArrayType<T>) => U
): U[];
```

### Implementation code 
I've tried to keep things as simple as possible. We utilize the [Array.prototype.flat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) that JS provides by default 🙏

```ts
export function deepFlatThenMap<T, U>(arr: readonly T[], iteratee?: (item: ExtractNestedArrayType<T>) => U) {
  const flattenList = arr.flat(Infinity) as ExtractNestedArrayType<T>[];

  if (!iteratee) {
    return flattenList;
  }

  return flattenList.map(item => iteratee(item));
}
```

<br />

### Default Usage
- Suggested deepFlatThenMap 
```ts
const arr = [1, 2, [3, 4, [5, 6]]];
deepFlatThenMap(arr); 
// type: number[] 
// value: [1, 2, 3, 4, 5, 6]
```
- Lodash flatMapDeep
```ts
const arr = [1, 2, [3, 4, [5, 6]]];
_.flatMapDeep(arr); 
// type: number[] 
// value: [1, 2, 3, 4, 5, 6]
```

### With Iteratee
- Suggested deepFlatThenMap
```ts
const arr = [1, 2, [3, 4, [5, 6]]];
deepFlatThenMap(arr, (item) => ({ id: item }));
// type: { id: number }[]
// value: [{ id: 1}, { id: 2}, { id: 3}, { id: 4}, { id: 5}, { id: 6}];
```
- Lodash flatMapDeep
```ts
const arr = [1, 2, [3, 4, [5, 6]]];
_.flatMapDeep(arr, (item) => ({ id: item }));
// type: { id: number | (number | number[])[] }[];
// value: [{ id: 1}, { id: 2}, { id: [3, 4, [5, 6]]}];
```

<br />

### Browser Compatibility
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

I think the compatibility of `flat` is now stable as well. 

<img width="773" alt="스크린샷 2024-07-04 오전 1 23 31" src="https://github.com/toss/es-toolkit/assets/64779472/7a0328bb-779d-4abf-91d1-7f45a317f852">

**Comment by ssi02014** [comment]
If you're comfortable with adding that `flatMapDeep`, I can work on it.

**Comment by raon0211** [comment]
As you mentioned, this can be easily implemented with modern JavaScript, such as `array.flat(Infinity).map(...)`.

However, we might implement `flatten` for performance reasons and to achieve feature parity with Lodash.

**Comment by ssi02014** [comment]
@raon0211 Great! So what about implementing `flattenDepth`, which does the same thing as `Array.prototype.flat` but performs better, and then building on that to implement `flatten(depth1)` and `flattenDeep`, `flatMapDeep` ?

https://github.com/toss/es-toolkit/issues/122#issuecomment-2209142717 
I tested the code I suggested in the comments above, which gives the same result but is much faster.
It also has the same return type as `Array.prototype.flat`.

**Comment by ssi02014** [comment]
@raon0211 
While `deepFlatThenMap` is actually simple to implement, `flat(Infinity).map()` is inconvenient to use from a type perspective. 

```ts
// as-is
const arr = [1, 2, [3, 4, [5, 6]]];
const result = arr.flat(Infinity).map((item) => item * 2);
/*
  TypeError: The left side of an arithmetic operation must be of type 'any', 'number', 'bigint', or enumeration.ts(2362)
(parameter) item: FlatArray<number | (number | number[])[], 0 | 1 | 2 | 3 | 4 | 5 | 6 | -1 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20>
*/
```
```ts
// to-be
const arr = [1, 2, [3, 4, [5, 6]]];
const result = deepFlatThenMap(arr, (item => item * 2)); // Behave as normal
// result: number[]
```

Therefore, we have proposed "deepFlatThenMap" to abstract it and allow for smooth type inference.

But if it doesn't fit the "es-toolkit" purpose, I'll close this issue and create a new issue for `flattenDepth`!

**Comment by raon0211** [comment]
I guess this is kind of a tricky problem!

As you mentioned, `arr.flat(Infinity).map(...)` has some issues in TypeScript.

I thought it should work well, but since `Infinity` is not a valid type literal in TypeScript (unlike `0`, `1`, and `1.5`), `arr.flat(Infinity)` doesn't work correctly. However, using `arr.flat(999)` mostly works; see [this issue](https://github.com/microsoft/TypeScript/issues/32277). So, this is a problem with TypeScript.

I think we should fix this with `flattenDeep`, like `flattenDeep(arr).map(...)`. Instead of `deepFlatThenMap`, it might be better to define a smaller function and compose it.

**Comment by raon0211** [comment]
Why not go with the following approach?

- Implement `flatten(arr, depth)` using your implementation of `flattenDepth`.
   - Instead of separating `flatten` and `flattenDepth`, merge them and set the default value of `depth` to `1`.
- Implement `flattenDeep` using `flatten`.

**Comment by ssi02014** [comment]
@raon0211 
Thanks for the nice comment. I agree with you.
I'll close this issue and I can work with `flatten(arr, depth)` as you suggested.  Is this okay?

**Comment by raon0211** [comment]
Sure :)
