### ISSUE TITLE
Incorrect documentation for `range` function

### ISSUE THREAD

**Issue by mass2527** [toss/es-toolkit#128]
```
 * @example
 * // Returns []
 * range(0, -4, -1);
 ```

This is a current example of the `range` function documentation.
However, it now returns `[0, -1, -2, -3]`.
What is the intended behavior of this function?

Does this function support a negative step or not?

I will fix this if you let me know the intended behavior.

**Comment by raon0211** [comment]
I think we should fix the docs to indicate it returns `[0, -1, -2, -3]`.

**Comment by raon0211** [comment]
Fixed the docs in https://github.com/toss/es-toolkit/commit/0e7e5c177cc311a36785ee759724fbe5467c91ea.
