### ISSUE TITLE
Support for `flatMap`

### ISSUE THREAD

**Issue by ssi02014** [toss/es-toolkit#168]
Implements [lodash's flatMapDepth](https://lodash.com/docs/4.17.15#flatMapDepth) based on `flatten`. 

### Suggested flatMap
```ts
function flatMap<T, U, D extends number = 1>(
  arr: readonly T[],
  iteratee: (item: T) => U,
  depth = 1 as D
): FlatArray<U[], D>[] {
  return flatten(arr.map(iteratee), depth);
}
```

The existing [Array#flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) is limited to a `depth of 1`. We can improve this inconvenience, and it's faster. 

<br />

```ts
const arr = [1, [2, 3], 4]

arr.flatMap((item) => [item, item]); // Array#flatMap
// return type: (number | number[])[]
// value: [1, 1, [2, 3], [2, 3], 4, 4]
```

<br />

💡 **Question: I'm wondering about the naming, should I go with `flatMap` like lodash? An alternative is `flattenMap`.** 

<br />

### Example
```ts
const arr = [1, [2, 3], 4]

flatMap(arr, (item) => [item, item]); // depth defulat: 1, It behaves the same as Array#flatMap. 
// return type: (number | number[])[]
// value: [1, 1, [2, 3], [2, 3], 4, 4]

flatMap(arr, (item) => [item, item], 1); // It behaves the same as Array#flatMap. 
// return type: (number | number[])[]
// value: [1, 1, [2, 3], [2, 3], 4, 4]

flatMap(arr, (item) => [item, item], 2);
// return type: number[]
// value: [1, 1, 2, 3, 2, 3, 4, 4]
```

## Note
[Array#flatMap - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap)

**Comment by ssi02014** [comment]
@raon0211 Can I proceed with the task? If you have any additional thoughts, I'd appreciate it. 🙏

**Comment by ssi02014** [comment]
Furthermore, if we implement `flatMap`, we can extend it to `flatMapDeep`.

**Comment by raon0211** [comment]
In general, I think `flatten` and `flatMap` is most used. So we could go on with `flatMap`.

**Comment by ssi02014** [comment]
@raon0211 Thank you so much for your feedback!
Great, I'll go ahead and work with `flatMap`.
