### ISSUE TITLE
[Feature]: Can't pass a callback function with arguments to the debounce function.

### ISSUE THREAD

**Issue by jungpaeng** [toss/es-toolkit#18]
https://github.com/toss/es-toolkit/blob/main/src/function/debounce.ts#L21

The func of the debounce function cannot be passed a function that takes arguments.
If you look at the usage of the debounce function, it doesn't always seem to be targeting functions with no arguments.

**Comment by jungpaeng** [comment]
https://github.com/toss/es-toolkit/blob/main/src/function/throttle.ts#L26

The same is true for the throttle function.

**Comment by raon0211** [comment]
Resolved by #26.
