### ISSUE TITLE
Improved Type System for Object Management in typescript

### ISSUE THREAD

**Issue by haejunejung** [toss/es-toolkit#182]
Hello, @raon0211!

When implementing an object utilities (pickBy, omitBy, etc...), why not add a way to easily use key and value types?

I propose adpoting an enhacned type system for managing objects in Typescript, leveraging features like `KeyOf` and `ValueOf` instead of relying on `keyof T` and `T[keyof T]`. I think this approach promotes type safety and clarity thoroughout the codebase.

```typescript
// KeyOf
export type KeyOf<T extends Record<PropertyKey, any>> = keyof T;

// ValueOf
export type ValueOf<T> = T extends Record<PropertyKey, infer V> ? V : never;
```

I think by incorporating types, it ensures that operations on objects are more robust and maintainable. If needed, can I placed in the `predicate` folder and submitted as a pull request with documentation and test?

**Comment by seungrodotlee** [comment]
I agree with this proposal!

I believe that creating and using utility types during the implementation of features will provide greater value to contributors and developers using this library.

To give an example of mine,  I'm currently working on`curry`(#135) and it is practically difficult to make `curry` work correctly in TypeScript without using utility types.

However, I don't think documentation or testing for these utility types is necessary. The essence of this library is to provide 'features' not 'types'. Therefore, I am currently writing utility types in the `src/_internal/types` directory. (I referred to other libraries like `es-hangul`, which write internal utilities in the `_internal` directory.)

Of course, if the utility types created during the implementation of features grow to a point where they offer additional value to developers on their own, we could consider providing a new library, such as `es-type`, that consolidates these utility types.

**Comment by haejunejung** [comment]
Oh, thanks for @seungrodotlee  commenting! 

I agree with the documentation and testing for these utility types is unnecessary. Moreover, the proposal to provide a utility type library like `es-type` also seems very promising.

However, I think the several parts in the current code written with `keyof T` and `T[keyof T]`. Would it be okay to implement `KeyOf` and `ValueOf` and to migrate to using these? I'm wondering if this might be unnecessary.

**Comment by raon0211** [comment]
Hello, thanks for your suggestion :) Meanwhile, I was wondering what would be the benefits for `KeyOf<T>` and `ValueOf<T>`. I thought `keyof T` and `T[keyof T]` are concise and descriptive.

**Comment by haejunejung** [comment]
Here’s why:

1. **Promotes Type Safety**: The traditional approach using keyof T and T[keyof T] provides type safety but can be verbose and less intuitive. The suggested approach using KeyOf and ValueOf offers a clearer and more concise way to express the types of keys and values in an object. By adopting KeyOf and ValueOf, we ensure that the types are always correctly inferred, reducing the risk of errors and making the codebase safer.

2. **Improves Readability**: Using KeyOf and ValueOf can significantly enhance readability, especially for those who might not be as familiar with TypeScript’s syntax. These aliases make the code more self-explanatory, improving overall comprehension. (This is particularly beneficial for documentation aimed at users of @toss/es-toolkit.)

3. **Ensures Consistency**: Defining these as types helps maintain consistency across a large codebase. Instead of repeatedly using keyof T and T[keyof T] in multiple places, employing these aliases makes the code more uniform. Additionally, it promotes the DRY (Don't Repeat Yourself) principle, reducing redundancy and simplifying maintenance.

**Additionally, here is some use cases.**
- [Next.js](https://github.com/vercel/next.js/blob/canary/packages/next/src/shared/lib/constants.ts), code line 5.

- [Nest.js](https://github.com/nestjs/nest/blob/master/packages/microservices/external/kafka.interface.ts), code line 387.

- [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/scratch-env/index.d.ts), code line  1.

- [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-table/index.d.ts), code line 69.

I am wondering your thought for this. 👀

**Comment by raon0211** [comment]
Hello, thanks for your opinion. 

I understand that `ValueOf<T>` might be more intuitive than `T[keyof T]` for people who are not familiar with TypeScript. On the other hand, I am not sure it promotes type safety or ensures consistency, because they basically mean the same thing and I guess it is a matter of style, so we might stick to either one.

My basic thoughts were that `ValueOf<T>` was not as intuitive for me; it could be `Required<T>[keyof T]` or `T[keyof T]` depending on the context. So I thought since the type definition is very simple, `T[keyof T]` would be less confusing. (The users of our library need to learn what `ValueOf<T>` exactly means, since it is not a built-in language construct).

As for `keyof T` and `KeyOf<T>`, I see little difference between them. If there is little difference, I wish we use the built-in types.

**Comment by haejunejung** [comment]
Thanks for your opinion! 👍 

Umm., Now that I think about it, I think it's a matter of style Like you said. Considering that users need to know more about `ValueOf<T>`, it seems right to use the built-in type. 

And, The `KeyOf<T>` does not provide any additional functionality over `keyof T`, it is just for intuitive. 

If this is not useful for you, I will close this issue.
