### ISSUE TITLE
compile mstar code with gfortran

### ISSUE THREAD

**Issue by bouchentouf12** [toss/es-toolkit#186]
bouchentouf@bouchentouf-desktop:~/soft/mstar-master/mstar$ make
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c read_mommat_pij_vasp.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c mstar.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c eigvs.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c read_numlines_vasp.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c read_mommat_pij.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c kdelta.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c read_numlines.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c eigvz.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c read_mommat_nb.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -I/include -fopenmp -g -fbacktrace -ffpe-summary=none  -c dgenen.f90
f951: Warning: Nonexistent include directory ‘/include’ [-Wmissing-include-dirs]
gfortran -L/lib/intel64 -lmkl_gf_lp64 -lmkl_sequential -lmkl_core -lpthread -fopenmp -ldl -g -fbacktrace -ffpe-summary=none  -o mstar read_mommat_pij_vasp.o mstar.o eigvs.o read_numlines_vasp.o read_mommat_pij.o kdelta.o read_numlines.o eigvz.o read_mommat_nb.o dgenen.o
/usr/bin/ld: eigvs.o: in function `eigvs_':
/home/bouchentouf/soft/mstar-master/mstar/eigvs.f90:44: undefined reference to `ssyevd_'
/usr/bin/ld: /home/bouchentouf/soft/mstar-master/mstar/eigvs.f90:61: undefined reference to `ssyevd_'
/usr/bin/ld: eigvz.o: in function `eigvz_':
/home/bouchentouf/soft/mstar-master/mstar/eigvz.f90:49: undefined reference to `cheevd_'
/usr/bin/ld: /home/bouchentouf/soft/mstar-master/mstar/eigvz.f90:67: undefined reference to `cheevd_'
collect2: error: ld returned 1 exit status
make: *** [makefile:43: mstar] Error 1

**Comment by raon0211** [comment]
Hello, closing this pull request because there is not much context in the description. Feel free to open a new one if you have issues :)
