### ISSUE TITLE
Support for `isSubset`

### ISSUE THREAD

**Issue by ssi02014** [toss/es-toolkit#193]
What if we added a function that returns a `boolean` whether the array in the first argument completely contains all the elements of the array given as the second argument (a subset) or not? 

In `es-toolkit` there is already a well-crafted `difference` function. Reusing it makes it simple to implement. 

While this can be implemented simply via `difference`, I thought it would be nice to provide a function with a clear purposeful name.

### Suggested isSubset
```ts
import { difference } from './difference.ts';

export function isSubset<T>(
  superset: readonly T[],
  subset: readonly T[]
): boolean {
  return difference(subset, superset).length === 0;
}
```

**Comment by raon0211** [comment]
This looks nice for me. Could you make a pull request?

**Comment by ssi02014** [comment]
@raon0211 Thank you! 
I'm going to work on `flatMap`, and then I'm going to work on `isSubset` as well.
