### ISSUE TITLE
Support for ```set``` function

### ISSUE THREAD

**Issue by de-novo** [toss/es-toolkit#201]
In reference to [PR #150](https://github.com/toss/es-toolkit/pull/150), it was suggested that implementing a type-safe set function would be beneficial. The existing lodash set function does not infer return types, requiring as type casting, which may lead to undetected developer errors. Thus, a set function that supports type inference is needed.

<img width="585" alt="스크린샷 2024-07-15 오전 9 24 58" src="https://github.com/user-attachments/assets/341ba13e-0865-4681-9ea6-059c828f7479">

**Comment by raon0211** [comment]
That's right, and I think `lodash` already does this...

**Comment by raon0211** [comment]
Note that [set will be added in the next es-toolkit/compat release](https://es-toolkit.slash.page/reference/compat/object/set.html).
