### ISSUE TITLE
Support for merge

### ISSUE THREAD

**Issue by RandomLove** [toss/es-toolkit#205]

**Comment by bovas85** [comment]
merge modifies the object so it's not something I'd support. You can create a copy using spread syntax or Object.assign but I would keep impure operations out of this imho

**Comment by robinloeffel** [comment]
What about making `merge` immutable, kind of like a `toMerged`, if you will? One of the main reasons I use `lodash-es` is their `merge` function, which, opposed to `Object.assign` or the spread operator, merges an object or array deeply, instead of just shallowly.

**Comment by bovas85** [comment]
yes that'd be ideal, agree

**Comment by raon0211** [comment]
I guess `merge` can be added to `es-toolkit/compat`, but not in `es-toolkit`. As @robinloeffel mentioned, `toMerged` which handles objects in an immutable way can be added in `es-toolkit`.

**Comment by seungrodotlee** [comment]
I'm wondering if someone is currently working on the `merge` and `toMerged` functions. If there is no ongoing work, I would like to implement them.

**Comment by raon0211** [comment]
Oh! Missed @seungrodotlee's comment. Sorry for this 😢 

`merge` and `mergeWith` was recently added in es-toolkit. Thanks for your suggestion!

- merge: https://es-toolkit.slash.page/reference/object/merge.html#merge
- mergeWith: https://es-toolkit.slash.page/reference/object/mergeWith.html#mergewith
- toMerged: https://es-toolkit.slash.page/reference/object/toMerged.html#tomerged

**Comment by robinloeffel** [comment]
@raon0211 Perfect, thanks!

**Comment by ivan-kleshnin** [comment]
Wow, mixing immutable and mutable functions with no clear distinction in naming sounds like a very bad idea.
