### ISSUE TITLE
Support for 'get' function

### ISSUE THREAD

**Issue by scarletborat** [toss/es-toolkit#215]
Hi @raon0211. 
Want to implement 'get' function from the list of #91.
Can I do it?

**Comment by raon0211** [comment]
Hello, would you mind if I implement the `get` and `set` functions?

**Comment by scarletborat** [comment]
Hello @raon0211, Sure ).
Is there some task I can help with?

**Comment by raon0211** [comment]
Thanks for helping us! We will organize what should be done and ask for help soon. (Probably this weekend..)

Note that [get will be added to es-toolkit/compat](https://es-toolkit.slash.page/reference/compat/object/get.html#get) in the next release :)
