### ISSUE TITLE
criteria for deleting compatibility test cases

### ISSUE THREAD

**Issue by sunrabbit123** [toss/es-toolkit#244]
Hello, I'm one of the people who wants to contribute.

I'm looking at compatibility
We have confirmed that some test cases are different from the actual test cases of rodash.

Some of the test cases have been deleted

Of course, those are not for me to contribute.

However, when it comes to things that are difficult to touch, such as `realm`
Whether to delete the test case or not

I wanted to ask you about the criteria for deleting the test case, so I wrote an issue.

example: https://github.com/toss/es-toolkit/commit/6739c840ed9960a333c61ae19776815623a38633

**Comment by raon0211** [comment]
Hello, could you refer to our [compatibility docs](https://es-toolkit.slash.page/compatibility.html#design-principles) for this? We actually have some criteria for moving test cases.
