### ISSUE TITLE
Testing the dist output?

### ISSUE THREAD

**Issue by fvsch** [toss/es-toolkit#254]
### The problem

While working on https://github.com/toss/es-toolkit/issues/216 to generate a cleaner `dist` folder (currently trying with Rollup instead of `tsup`), I’m having trouble making sure I don't regress the current build output.

The existing test suites seem to be pulling code from `src` directly:

- Benchmark tests tend to import from `'es-toolkit'` or `'es-toolkit/{category}'`, and it looks like Vitest is using the `package.json#exports` field to resolve that to TypeScript files in `src`:

```jsonc
{
  // …
  "exports": {
    ".": "./src/index.ts",
    "./array": "./src/array/index.ts",
    "./compat": "./src/compat/index.ts",
    "./function": "./src/function/index.ts",
    "./math": "./src/math/index.ts",
    "./object": "./src/object/index.ts",
    "./predicate": "./src/predicate/index.ts",
    "./promise": "./src/promise/index.ts",
    "./string": "./src/string/index.ts",
    "./package.json": "./package.json"
  },
  // …
}
```

- Unit tests are located alongside the TypeScript sources and tend to have two types of imports:
    - Relative, without an extension: `import { functionName } from './functionName';`
    - Relative, with an extension: `import { functionName } from './functionName.ts';`

As a result, we can't use those tests to verify that the build output in `dist` is correct and doesn't have issues like missing functions or files, flagrant runtime errors when evaluating a module, or more subtle bugs introduced by transpiling.

### Possible solutions

My original idea was to reuse existing unit tests (perhaps not the benchmarks) and forcing Vitest to resolve imports to the ESM or CJS builds. This can be done in `vitest.config.mts` with something like:

```ts
import path from 'node:path';
import { defineConfig } from 'vitest/config';

function libAliases() {
  const index = `index.${process.env.TEST_LIB_EXT || 'ts'}`;
  const baseDir = path.join(import.meta.dirname, index.endsWith('.ts') ? 'src' : 'dist');
  return [
    {
      find: /^es-toolkit$/,
      replacement: path.join(baseDir, 'index.js'),
    },
    {
      find: /^es-toolkit\/([a-z]+)$/,
      replacement: path.join(baseDir, '$1', 'index.js'),
    },
  ];
}

export default defineConfig({
  resolve: {
    alias: libAliases(),
  },
  // …
});
```

Then by defining `TEST_LIB_EXT=js` or `TEST_LIB_EXT=mjs`, you can run tests using the build outputs in `dist`, provided that all tests import library functions from `es-toolkit` or `es-toolkit/{category}`.

The issue with this approach is that it's maybe overkill to re-run all unit tests twice (once for the ESM build and one for the CJS build) just to verify that the build output is not borked.

Another approach would be to write some kind of integration test that:

1. packages the library with `yarn pack` (with the `prepack` script building the `dist` folder);
2. uses the resulting `package.tgz` as the source of the `es-toolkit` package (e.g. in a workspace in a subfolder there could be a `package.json` with: `{ "dependencies": {"es-toolkit": "../package.tgz"} }`);
3. contains a few integration tests that check what you get when importing from `es-toolkit` or `es-toolkit/{category}`.

I don't have much experience with those kinds of checks. Maybe there's an even simpler way to do a very basic smoke test, and that would be enough?

**Comment by raon0211** [comment]
As you mentioned, we currently don't have integration tests to check our build output. 

In our company, we usually approach this with what you mentioned last:

1. Package the library with yarn pack (with the prepack script building the dist folder);
2. Use the resulting package.tgz as the source of the es-toolkit package (e.g. in a workspace in a subfolder there could be a package.json with: { "dependencies": {"es-toolkit": "../package.tgz"} });
3. Run a few integration tests that check what you get when importing from es-toolkit or es-toolkit/{category}.

I guess we could add this step and run this in our CI.

**Comment by fvsch** [comment]
Looks like running `@arethetypeswrong/cli` on the output in CI might be a good first step.
