### ISSUE TITLE
is it available on CDN anywhere?

### ISSUE THREAD

**Issue by Claire** [toss/es-toolkit#256]
if using es-toolkit as lodash replacement is there a cdn hosting min (and unminified) versions?

**Comment by raon0211** [comment]
Hello, I think you can use unpkg.com, like https://unpkg.com/es-toolkit@1.12.0/dist/index.js. We will document this.

**Comment by raon0211** [comment]
We just documented how to access `es-toolkit` in browsers.

https://es-toolkit.slash.page/installation.html#browsers
