### ISSUE TITLE
Support for compat/faltten, flatten{Depth, Deep}

### ISSUE THREAD

**Issue by dayongkr** [toss/es-toolkit#262]
In lodash, They wrote test cases for three methods in [one file](https://github.com/lodash/lodash/blob/main/test/flatten-methods.spec.js). 

``` javascript
describe('flatten methods', () => {
    const array = [1, [2, [3, [4]], 5]];
    const methodNames = ['flatten', 'flattenDeep', 'flattenDepth'];

...
```

Do we write them separately, or do we follow the same approach?

**Comment by raon0211** [comment]
While modernizing the test code, we try to keep them separate. 

It's a little bit of work, but I think in the long run it will keep our readability of the code.

**Comment by dayongkr** [comment]
> While modernizing the test code, we try to keep them separate. 
> 
> It's a little bit of work, but I think in the long run it will keep our readability of the code.

Ok, then i will add test codes separately.
