### ISSUE TITLE
Support for is{ArrayLike, Function}

### ISSUE THREAD

**Issue by dayongkr** [toss/es-toolkit#263]
`isArrayLike` need in a testcase for `compat/flatten` (#262)

``` javascript
it('should return an empty array for non array-like objects', () => {
```

And `isFunction` and `isLength` need in `isArrayLike`

**Comment by raon0211** [comment]
isLength has been added in the previous version, but I think the other functions need to be implemented. Would you help us?

**Comment by dayongkr** [comment]
> isLength has been added in the previous version, but I think the other functions need to be implemented. Would you help us?

Of course, I am going to implement!
