### ISSUE TITLE
Publishing issues with the browser.global.js build

### ISSUE THREAD

**Issue by fvsch** [toss/es-toolkit#284]
The browser build, as published today (https://unpkg.com/browse/es-toolkit@1.13.1/umd/browser.global.js), has a couple issues:

1. It's referencing a sourcemap (``), but that sourcemap is not published in the package (https://unpkg.com/es-toolkit@1.13.1/umd/browser.global.js.map is a 404).
2. Its path is `umd/browser.global.js`, but its format is not UMD, it's an IIFE with a side-effect of adding an object as `window._`. [UMD is a specific format](https://github.com/umdjs/umd), and it would be best to not advertise UMD when that format is not actually provided.

Personally, I don't think UMD is useful nowadays. Using a simple IIFE format is a fine approach for CDN use. So I would just change the path, maybe output this bundle at `dist/browser.global.js`?

**Comment by raon0211** [comment]
I think we should check why the source map is not published with the package here. 

As you mentioned, umd is a specific module format. I think we should change the filename to what you've proposed.

**Comment by fvsch** [comment]
> I think we should check why the source map is not published with the package here.

This was because the `umd` folder was not listed in `package.json#files`.

The JS bundle itself was added to the package because it's referenced in `package.json#publishConfig#browser`. (Entrypoints declared in `package.json` always get added by package managers to the package, even if not listed in `package.json#files`.)

This was fixed by adding `umd` to `package.json#files` in #255, but I'm moving this bundle in #314.
