### ISSUE TITLE
Are the root *.d.ts files still useful?

### ISSUE THREAD

**Issue by fvsch** [toss/es-toolkit#287]
The `yarn build` script runs this script:

https://github.com/toss/es-toolkit/blob/ef39661b63b5ca7c0156444c11e1084307040e90/.scripts/postbuild.sh#L1-L9

Which adds a few `.d.ts` files at the root of the project, which then get picked up (via `package.json#files`) in the final package, for example:
https://unpkg.com/browse/es-toolkit@1.13.1/array.d.ts

As far as I can tell, those files are not referenced in `package.json#types` or anywhere else. They look like leftovers from previous iterations of this package.

Do they still have a use, or could they be removed?

**Comment by raon0211** [comment]
Actually, these type declarations are used for `"moduleResolution" "Node10"`, which is the default module resolution in TypeScript. Without these declarations, we cannot use named exports in legacy projects.
