### ISSUE TITLE
AbortError and TimeoutError classes exported by mistake?

### ISSUE THREAD

**Issue by fvsch** [toss/es-toolkit#289]
Looking at the current build of this package, the root entrypoint exports two classes:

- `AbortError` (from https://github.com/toss/es-toolkit/blob/main/src/error/AbortError.ts)
- `TimeoutError` (from https://github.com/toss/es-toolkit/blob/main/src/error/TimeoutError.ts)

Those classes are not listed in the reference on https://es-toolkit.slash.page/, and only one appears in the search, because it's mentioned on that page:
https://es-toolkit.slash.page/reference/promise/timeout.html

Are those classes exported on purpose?

- If yes, they may require some documentation.
- If not, it looks like this line is a mistake:

https://github.com/toss/es-toolkit/blob/ef39661b63b5ca7c0156444c11e1084307040e90/src/index.ts#L58

**Comment by raon0211** [comment]
Added docs in this commit. Thanks for pointing this out!

https://github.com/toss/es-toolkit/commit/f99a6b26c3297647d0f3e8785c905620e72f6346
