### ISSUE TITLE
Support for `isString`

### ISSUE THREAD

**Issue by TiBianMod** [toss/es-toolkit#300]
Support for [isString](https://lodash.com/docs/4.17.15#isString) is needed.

**Comment by uussong** [comment]
@raon0211  I'd like to work on this issue. Is that okay with you?

**Comment by raon0211** [comment]
@uussong Sure!

**Comment by injae-kim** [comment]
PR: https://github.com/toss/es-toolkit/pull/379 PTAL! 🙇
