### ISSUE TITLE
Support for `upperCase`

### ISSUE THREAD

**Issue by TiBianMod** [toss/es-toolkit#304]
Support for [upperCase](https://lodash.com/docs/4.17.15#upperCase) is needed.

**Comment by ivan-kleshnin** [comment]
How it that different from `str.toUpperCase`? 
I thought the goal of this library is to not reimplement functionality that exists (and is properly typed) in JS/TS natively 🤔

**Comment by TiBianMod** [comment]
@ivan-kleshnin is not the same as `str.toUpperCase()`, take a look on lodash [upperCase](https://lodash.com/docs/4.17.15#upperCase) 

```js
_.upperCase('--foo-bar'); // => 'FOO BAR'
 
_.upperCase('fooBar'); // => 'FOO BAR'
 
_.upperCase('__foo_bar__'); // => 'FOO BAR'
```

**Comment by TiBianMod** [comment]
already implemented by PR https://github.com/toss/es-toolkit/pull/402
