### ISSUE TITLE
Link error in Korean docs

### ISSUE THREAD

**Issue by sadobass** [toss/es-toolkit#311]
Seems that `/ko/` is missing in docs for forEachRight and negate, which makes us move to the English documentation.

ko.mts file:
72line : { text: 'forEachRight', link: '/reference/array/forEachRight' }, ==> { text: 'forEachRight', link: '**/ko**/reference/array/forEachRight' },
128line : { text: 'negate', link: '/reference/function/negate' }, ==> { text: 'negate', link: '**/ko**/reference/function/negate' },

**Comment by raon0211** [comment]
Thanks! Fixed this link error.
