### ISSUE TITLE
Simple One-Line Helpers

### ISSUE THREAD

**Issue by ofabel** [toss/es-toolkit#318]
Since I don't like anonymous functions within a chain of `map`, `filter`, `then`, ... calls. For example the following code snippet:

```typescript
const getAvatar = (id: number): Promise<string> => 
    fetch(`/api/users/${id}/avatar`)
        .then(response => response.blob())
        .then(blob => URL.createObjectURL(blob));
```

I would prefer to implement this as follows:

```typescript
const toBlob = (response: Response): Blob => response.blob();
const toObjectUrl = (blob: Blob): string => URL.createObjectURL(blob);

const getAvatar = (id: number): Promise<string> => 
    fetch(`/api/users/${id}/avatar`)
        .then(toBlob)
        .then(toObjectUrl);
```

So I like to ask with this issue: Are such little helper functions (`toBlob`, `toObjectUrl`, ...) something you could imagine to be part of the `es-toolkit` collection? I would be willing to contribute this part myself.

**Comment by raon0211** [comment]
Hello, thanks for your suggestion! 

While I agree that these functions can help the simplicity of codebase, I think these are a matter of style, which is out of scope of es-toolkit.
