### ISSUE TITLE
Enhancing `toFilled` Function to Support as const

### ISSUE THREAD

**Issue by wondonghwi** [toss/es-toolkit#326]
Hello, would it be possible to update the toFilled function to support readonly arrays and ensure it works when arrays are defined with as const? 

This enhancement will allow developers to use the function with immutable arrays, ensuring the original array remains unchanged. 

Supporting as const is important because it allows for better type safety and optimization, preventing accidental mutations and providing more predictable and maintainable code. Since the toFilled function ensures the original array remains immutable, adding support for as const will align perfectly with its design principles. I look forward to seeing these changes implemented. 

If it's okay, may I work on this improvement?

AS_IS
![image](https://github.com/user-attachments/assets/c2a52e9d-cc08-44f2-a29a-dae39fb4d7e5)

TO_BE
![image](https://github.com/user-attachments/assets/505cda13-9449-4cef-97b7-11fceea2fcb1)

**Comment by raon0211** [comment]
You're right, we should accept readonly arrays here.
