### ISSUE TITLE
orderBy keys don't support nested keys

### ISSUE THREAD

**Issue by rtwayland** [toss/es-toolkit#328]
Lodash's `orderBy` allows nested keys (`orderBy(array, ['episode.viewers'], ['asc'])`), whereas es-toolkit's `orderBy` does not.

[Example](https://stackblitz.com/edit/vitejs-vite-1zgutf?file=src%2FApp.tsx)

**Comment by raon0211** [comment]
Yup, I think we should fix them in `es-toolkit/compat`. We will fix them soon!

**Comment by dayongkr** [comment]
Today, I am going to add `orderBy` in `es-toolkit/compat`.

**Comment by dayongkr** [comment]
I am handling this issue.

May be I can created PR tonight.
