### ISSUE TITLE
Support for `forEach`

### ISSUE THREAD

**Issue by haejunejung** [toss/es-toolkit#335]
Hello, @raon0211!
If you need `forEach`, Can I work it? 

If you don't mind working with it, in the case of `forEach`, it only applied to arrays, but I understand that compat(lodash) supports some objects. So, I plan to ensure that only compat support objects.

**Comment by raon0211** [comment]
I guess this is necessary. Thanks for helping us!

**Comment by Aleksandern** [comment]
@haejunejung 
Do you plan to do `forEach` for objects?

**Comment by haejunejung** [comment]
@Aleksandern 
Oh.., I completely forgot about this issue, I'm sorry. I think it would be nice to work on it if you want.
