### ISSUE TITLE
cloneDeep is not an export of es-toolkit

### ISSUE THREAD

**Issue by tsteuwer-accesso** [toss/es-toolkit#336]
`cloneDeep` was added through [this PR](https://github.com/toss/es-toolkit/pull/199) but is not exported from `es-toolkit` when importing it in our application.

![image](https://github.com/user-attachments/assets/e1c8f02e-39a7-4781-a98c-4cc019bdfa7f)

Looking into the node_modules, I can also see that `dist/object/` has no file named `cloneDeep`:

![image](https://github.com/user-attachments/assets/e03ab6a5-ad1f-4b78-9812-1ee61fde6560)

It's stated you can use this on the documentation site https://es-toolkit.slash.page/reference/object/cloneDeep.html, but has this not actually been exported yet?

**Comment by fvsch** [comment]
The last stable release, `v1.13.1`, was two weeks ago according to:

- https://github.com/toss/es-toolkit/releases
- https://www.npmjs.com/package/es-toolkit?activeTab=versions

There are `dev` releases which should contain these changes, if you need them right now.

**Comment by tsteuwer-accesso** [comment]
Ahh ok, I thought that since it was published to the website that it should be available in the general release. Thanks

**Comment by leokang94** [comment]
I agree with @tsteuwer-accesso. In my opinion, if an implementation is not yet released, it's a good idea to tag the docs with `soon`. I'm here because of this problem too 😂
