### ISSUE TITLE
feature request: how to use shuffle by key 

### ISSUE THREAD

**Issue by reslear** [toss/es-toolkit#348]
```function shuffle<T>(arr: T[], key: string): T[];```

**Comment by raon0211** [comment]
Hello, thanks for opening the issue. 

Could you elaborate on how the `key` behaves?

**Comment by reslear** [comment]
hi @raon0211 sorry for the lack of an example, i mean key index replacement, but maybe it's outside the scope:

```ts
const arr = [
  {
    index: 10
    name: 'xyz'
  },
  {
    index: 5
    name: 'abc'
  }
]

// expected 
[{ index: 10, name: 'abc'}, { index: 5, name: 'xyz' }] 

// current solution 
shuffle(arr).map( (_,i) => {..._, index: i})

// feature solution
shuffle(arr, 'index')
```

I think it's definitely out of scope, so I'll close issue. Lol
