### ISSUE TITLE
Mismatch between docs and 1.13.1-latest 

### ISSUE THREAD

**Issue by WrylyRiley** [toss/es-toolkit#360]
I notices an odd mismatch today when trying to use `object/mapValues`

1. [The doc](https://es-toolkit.slash.page/reference/object/mapValues.html) for that function exists, but doesn't indicate a version that the function is available in 
2. `1.13.1-latest` build on npm does not have this function 
3. `1.13.1-dev.383` build on npm does have this function

I'm not sure I have a recommendation here, but I figured I'd bring it up nonetheless.

**Comment by raon0211** [comment]
You're right. `v1.14.0` was released today, could you give it a try?

**Comment by WrylyRiley** [comment]
Yeah, definitely! I'll get it installed tomorrow. Thanks!

**Comment by raon0211** [comment]
Thanks! Feel free to open the pull request if it's not working.
