### ISSUE TITLE
Support `AbortSignal` to `debounce` & `delay` for improved cancellation

### ISSUE THREAD

**Issue by jchoi-prestolabs** [toss/es-toolkit#37]
The [`debounce`](https://es-toolkit.slash.page/reference/function/debounce.html) function already supports cancellation through its return value, but its usability would improve if it also supported cancellation via [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal), which is [implemented in all major web browsers and JavaScript runtimes](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal#browser_compatibility).

It would also be great to add a cancel feature to the [`delay`](https://es-toolkit.slash.page/reference/promise/delay.html) function, and using `AbortSignal` here as well would be a good idea.

**Comment by jchoi-prestolabs** [comment]
Sure, I have no plan to work for this now.

**Comment by raon0211** [comment]
It would help if we could make `delay` throw `new Error('The operation was aborted')` if it is aborted :) (Like in [undici](https://github.com/nodejs/undici/blob/main/lib/core/errors.js#L78) of Node.js)

**Comment by raon0211** [comment]
This issue was resolved by #45 and #52. Thanks for your contribution, @Hanna922 !
