### ISSUE TITLE
Add custom order function in `es-toolkit/compat`

### ISSUE THREAD

**Issue by dayongkr** [toss/es-toolkit#370]
We don't have custom order function feature in `es-toolit/compat`

`lodash` don't add this case in test case. So I accidentally forgot to add it

I think we have to add this feature for compatibility.

**Comment by dayongkr** [comment]
We can check this feature in `lodash`'s comments.

https://github.com/lodash/lodash/blob/6a2cc1dfcf7634fea70d1bc5bd22db453df67b42/src/orderBy.ts#L27

**Comment by raon0211** [comment]
Does lodash support custom order functions? I couldn't find in its documentation.

**Comment by dayongkr** [comment]
And this is a code for implement this feature

https://github.com/lodash/lodash/blob/6a2cc1dfcf7634fea70d1bc5bd22db453df67b42/src/.internal/compareMultiple.ts#L26

**Comment by dayongkr** [comment]
We have to more be careful for implementing `es-toolkit/compat`

**Comment by dayongkr** [comment]
> And this is a code for implementing this feature.
> 
> https://github.com/lodash/lodash/blob/6a2cc1dfcf7634fea70d1bc5bd22db453df67b42/src/.internal/compareMultiple.ts#L26

This code was added to the main branch in 2018 but was never actually deployed to production, so it seems unnecessary to implement it.

I apologize for the confusion. Thank you.
