### ISSUE TITLE
Support for `compat/indexOf`

### ISSUE THREAD

**Issue by dayongkr** [toss/es-toolkit#377]
I think ES already has a `Array.prototype.indexOf` function, so we don't need in `es-toolkit`.

So I am going to implement only in `es-toolkit/compat`

**Comment by dayongkr** [comment]
`Array.prototype.indexOf` can't find `NaN`.

So how about add this function also in `es-toolkit`?

**Comment by raon0211** [comment]
I guess supporting `indexOf` in es-toolkit is out of scope, because we have other native APIs like `Array#findIndex` and `Array#includes` to properly support `NaN`s, anyway.

**Comment by dayongkr** [comment]
I asked how much simplicity es-toolkit aims for! Thank you!
