### ISSUE TITLE
No `LICENSE` file

### ISSUE THREAD

**Issue by ho991217** [toss/es-toolkit#38]
Can't find the `LICENSE` file anywhere in the repo. Therefore the link in the README is broken.

<img width="2055" alt="스크린샷 2024-06-13 13 31 36" src="https://github.com/toss/es-toolkit/assets/84632077/067e80bf-cba8-4cdf-8679-50a12c7f465e">

**Comment by raon0211** [comment]
This was resolved in https://github.com/toss/es-toolkit/commit/921a5e029274791ae6628db2f70a0743eed4196d. Thanks!
