### ISSUE TITLE
Support custom key functions in `es-toolkit/orderBy` and `es-toolkit/compat/orderBy`

### ISSUE THREAD

**Issue by dayongkr** [toss/es-toolkit#383]
## Problems

1. At now, we have a custom key function in `sortBy`, but `orderBy` doesn't have this feature.

Maybe, this makes confusion.

<img width="673" alt="Screenshot 2024-08-15 at 10 36 53 PM" src="https://github.com/user-attachments/assets/3008ff6c-b924-4660-a5e2-486f7a396034">

2. `lodash/orderBy` also supports this feature, but our `es-toolkit/compat/orderBy` doesn't support it.

## Solutions

1. Add it in `es-toolkit/orderBy`.
2. Add it in `es-toolkit/compat/orderBy`.

But after we also supports it in `es-toolkit/orderBy`, then  `es-toolkit/orderBy` looks like duplication of `es-toolkit/sortBy`.

> Difference of these functions is just it has a `order` argument or not.

So I think we have to integrate codes of these functions.

## Related issue

> https://github.com/toss/es-toolkit/issues/361#issuecomment-2280358793
> I guess in this case, the ideal way of using `orderBy` would be:
> 
> ```ts
> orderBy(data, x => x.value.toString(), ["asc"])
> ```
> 
> This would ensure that all numbers and strings are converted into string before comparison.

**Comment by dayongkr** [comment]
I will work separately with two PRs.

At first, I will make a PR for supporting custom key functions in `es-toolkit/compat/orderBy`.

And a rest of PR is supporting it in `es-toolkit/orderBy` and integrating with a `es-toolkit/sortBy`

**Comment by dayongkr** [comment]
If we add this feature in `es-toolkit/orderBy`, then how about makes `orderBy` deprecated and add a `orders` arguments in `sortBy`.

Two functions is too similar.

**Comment by raon0211** [comment]
We might support both `sortBy` and `orderBy`, even though they’re pretty similar.

`sortBy` usually sorts in ascending order, like `Array#sort`. If we need to sort in descending order, that’s where `orderBy` comes in.

**Comment by dayongkr** [comment]
> We might support both `sortBy` and `orderBy`, even though they’re pretty similar.
> 
> `sortBy` usually sorts in ascending order, like `Array#sort`. If we need to sort in descending order, that’s where `orderBy` comes in.

Almost programming languages have one sort function that has a reverse option, And javascript also have one sort function that has custom compare function.

And if we supports this feature in `orderBy` then `sortBy` code will be like this:

``` typescript
export function sortBy<T extends object>(arr: T[], criteria: Array<((item: T) => unknown) | keyof T>): T[] {
      return orderBy(arr, criteria, ['asc']);
      // or return orderBy(arr, criteria, criteria.map(() => 'asc');
}
```

If this is ok, then I will create PR for supporting this feature in `orderBy` and changing `sortBy` codes to above codes.

**Comment by raon0211** [comment]
I think what the direction of what you suggested is great.

**Comment by dayongkr** [comment]
I close the related PR by mistake. I will open the same PR soon.
