### ISSUE TITLE
Support for `pad`

### ISSUE THREAD

**Issue by pkovzz** [toss/es-toolkit#386]
The library already provides the [padStart](https://github.com/toss/es-toolkit/issues/280) and [padEnd ](https://github.com/toss/es-toolkit/issues/332)functions, so using them, we could support the [pad](https://lodash.com/docs/4.17.15#pad) function as well! 
However, unlike `padStart` and `padEnd`, `pad` does not part of the native API. Can I work on this? If so, does it belong to the `compat` or `string` module?

**Comment by raon0211** [comment]
It would be a great help if you would work on this! It would belong to `string` module since there isn't a corresponding native API.

**Comment by dayongkr** [comment]
If you are not working on, then can i work this?

**Comment by pkovzz** [comment]
Sorry, I’ve been busy for the last couple of weeks. I’ve planned to create a pull request this weekend.
