### ISSUE TITLE
Support for `parallel` 

### ISSUE THREAD

**Issue by jiwooproity** [toss/es-toolkit#387]
Hello!

I hope to support `parallel` promise functions. It can be resolve promise function in parallel.

For example
```typescript
const getUser = () => {
  return new Promise(resolve => resolve({ name: 'toss-developer' }));
};

const getStatus = (ms: number) => {
  return withTimeout(() => new Promise(resolve => resolve({ status: 'login' })), ms);
};

const promises = {
  getUser,
  getStatus,
};

const params = {
  getStatus: 200,
};

const [user, status] = await parallel(promises, params);
```

How do you think this `parallel` function? is it useful?
if think useful and agree, i can work on it.

**Comment by raon0211** [comment]
Hello :) Thanks for your suggestion! 

In my opinion, using `Promise.all(...)` would be similar with this use case.

```tsx
const [user, status] = await Promise.all([
  getUser(),
  getStatus(200),
]);
```

The design principle of es-toolkit is to use native APIs if possible.

**Comment by jiwooproity** [comment]
@raon0211 Thank you for your review. i undestand this opinion,
And i guess too, if i have any good ideas for using the native APIs in the future, i will suggest it again!
and sorry
