### ISSUE TITLE
Support for `findKey`

### ISSUE THREAD

**Issue by jonahisadev** [toss/es-toolkit#441]
Support for [findKey](https://lodash.com/docs/4.17.15#findKey)
I will implement this and open a PR

Please let me know if this is unnecessary, I am just looking to implement missing functionality.

**Comment by raon0211** [comment]
I think this is necessary. You could open a pull request!

**Comment by jonahisadev** [comment]
Work got super busy for me right after I said I'd do this. Looks like someone else got to it a little while ago.
