### ISSUE TITLE
Upgrade Node.js from version 20 to 22 following the october LTS change

### ISSUE THREAD

**Issue by dayongkr** [toss/es-toolkit#498]
The upcoming transition of Node.js 22 to LTS in October requires updating the current Node.js version from 20 to 22.

This upgrade simplifies the codebase by enabling the use of new Set-related methods and the others.

**Comment by raon0211** [comment]
`es-toolkit` will always support the oldest LTS version (currently we're supporting Node.js 18 LTS), so even Node.js 22 is released, we will still have to support Node.js 20.

**Comment by dayongkr** [comment]
> `es-toolkit` will always support the oldest LTS version (currently we're supporting Node.js 18 LTS), so even Node.js 22 is released, we will still have to support Node.js 20.

oh i was misunderstanding, Thanks!
