### ISSUE TITLE
Support for `random`

### ISSUE THREAD

**Issue by sossost** [toss/es-toolkit#51]
What if you could support a `random` function that returns a random number for a specific range? I think it would be useful in many different situations.
I would like to work on this if it is possible.

**Comment by raon0211** [comment]
This would be helpful. 

What about adding `random` which returns any floating point number and `randomInt` which returns any integer?

```
import { random, randomInt } from 'es-toolkit';

random(0, 5) // returns any numbers between 0 (inclusive) and 5 (exclusive), e.g. 0, 0.1, 1.4, 3, 4.2131 ...
randomInt(0, 3) // returns any integer between 0 (inclusive) and 3 (exclusive), e.g. 0, 1, 2.
```

**Comment by raon0211** [comment]
I find [the signature of lodash's random function](https://lodash.com/docs/4.17.15#random) quite confusing.

**Comment by sossost** [comment]
> I find [the signature of lodash's random function](https://lodash.com/docs/4.17.15#random) quite confusing.
I agree with you. 

I was wondering about the implementation direction, so thank you for your help.
