### ISSUE TITLE
Allow readonly array to be passed as keys in `pick` (and potentially other utils)

### ISSUE THREAD

**Issue by wojtekmaj** [toss/es-toolkit#526]
After replacing lodash with es-toolkit, I got:

> Error: /packages/plugin-npm/sources/npmHttpUtils.ts(288,19): error TS2345: Argument of type 'readonly ["name", "dependencies", ... <truncated for clarity\>]' is not assignable to parameter of type '("dependencies" | "name" | ...\<truncated for clarity\>)[]'.

**Comment by wojtekmaj** [comment]
Maybe related to #413, but #413 does not mention `pick`.

**Comment by raon0211** [comment]
Let me check if other any other functions or compatibility function is not accepting `readonly` arrays.

**Comment by raon0211** [comment]
Hi, this bug was resolved in es-toolkit v1.19.0.

We added most of the missing readonly properties, especially for `pick`.
