### ISSUE TITLE
`drop` - Compatibility with lodash original functions

### ISSUE THREAD

**Issue by DonghyunKim98** [toss/es-toolkit#531]
### In lodash

```typescript
function drop(array, n = 1) {
    const length = array == null ? 0 : array.length;
    return length ? slice(array, n < 0 ? 0 : toInteger(n), length) : [];
}
```

The code is written assuming that null enters array. However, in drop.ts of es-toolkit, the type of array is written as `readonly T[]`, so null cannot be entered at all.

Of course, the code below is not intuitive, but shouldn't exception handling be done for compatibility?
```
drop(null,2); // expected []
```

**Comment by raon0211** [comment]
We might add these kind of behavior in our compatibility library. Please refer to functions like [orderBy](https://github.com/toss/es-toolkit/blob/main/src/compat/array/orderBy.ts#L41).
