### ISSUE TITLE
Support for `maxBy`

### ISSUE THREAD

**Issue by l2hyunwoo** [toss/es-toolkit#55]
Support `max` function in two ways would be helpful.

1. if input param's type is `number[]`: same as lodash's `max`
2. if input param's type is `any[]`: same as lodash's `maxBy`

**Comment by raon0211** [comment]
Hello, thanks for your suggestion :)

We might support `maxBy`, but would it be helpful to have `max`, considering we currently have `Math.max` already in JavaScript?

```tsx
Math.max(...[1, 2, 3]) === 3
```

**Comment by l2hyunwoo** [comment]
> but would it be helpful to have max, considering we currently have Math.max already in JavaScript?

Aha! I guess we don't need to reimplement something that's already implemented. Then how about support `maxBy` operator of array, [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)?

Like below,

```typescript
const map = new Map()
map.set('a', {age: 10, priority: 3})
map.set('b', {age: 12, priority: 2})
map.set('c', {age: 14, priority: 1})
const maxOfAge = map.maxBy((element) => { element.age }) // ['c', {age: 14, priority: 1}]
const maxOfPriority = map.maxBy((element) => { element.priority }) // ['a', {age: 10, priority: 3}]
```

I think `maxBy` operator is useful not just array but also object using iterator pattern.

**Comment by l2hyunwoo** [comment]
If it's reasonable approach, I'd like to contribute it.

**Comment by raon0211** [comment]
Yes, having `maxBy` would be helpful :) 

I think supporting `maxBy` for only arrays is fine for now, because 

- We don't support `Map`s or `Set`s right now in other cases, and
- Every iterable object can converted to arrays in JavaScript.

For instance, `maxBy` of `Map`s can be implemented like:

```tsx
const map = new Map()
map.set('a', {age: 10, priority: 3})
map.set('b', {age: 12, priority: 2})
map.set('c', {age: 14, priority: 1})

maxBy([...map.entries()], ([, element]) => element.priority);
```

**Comment by l2hyunwoo** [comment]
@raon0211 👍🏻 Thanks for kind suggestion. I'll try it!
