### ISSUE TITLE
`uniqBy` is slower than lodash

### ISSUE THREAD

**Issue by changwoolab** [toss/es-toolkit#56]
Currently, `uniqBy` function is implemented with time complexity O(N^2) while lodash's implementation is O(N).

I just report this as an issue because I failed to make this faster than lodash. Even though I made it O(N) using `Map` or `Set`, lodash was much faster than my implementation when the array's length was more than 10000.

Below is the benchmark for `uniqBy`.

```ts
const array = Array.from({ length: 10000 }, () => Math.random() * 1000);

describe('uniqBy', () => {
  bench('es-toolkit', () => {
    uniqByToolkit(array, Math.floor);
  });

  bench('lodash', () => {
    uniqByLodash(array, Math.floor);
  });
});
```

1. length = 100
<img width="793" alt="Screenshot 2024-06-15 at 2 04 21 PM" src="https://github.com/toss/es-toolkit/assets/64240134/3f0dfe45-f8a5-40ef-bcf9-a68ec0159ce7">

2. length = 1000
<img width="781" alt="Screenshot 2024-06-15 at 2 03 36 PM" src="https://github.com/toss/es-toolkit/assets/64240134/c38486e7-2c46-4ccf-95de-0d2d20b8a6da">

3. length = 10000
<img width="776" alt="Screenshot 2024-06-15 at 2 04 53 PM" src="https://github.com/toss/es-toolkit/assets/64240134/6dd4c80b-a200-441a-afe6-500abccacaba">

**Comment by raon0211** [comment]
Seems that it can be improved if we choose this implementation:

```tsx
export function uniqBy<T, U>(arr: readonly T[], mapper: (item: T) => U): T[] {
  const map = new Map<U, T>();

  for (const item of arr) {
    const key = mapper(item);

    map.set(key, item);
  }

  return Array.from(map.values());
}

**Comment by raon0211** [comment]
Fixed in commit https://github.com/toss/es-toolkit/commit/60e79741271e645bfa551f708466e43b136f69b1#diff-bc0ac1e1ab023f0668ee56519ccc643964772b0baa9cdb2fdde57abb397f474fL18.

**Comment by changwoolab** [comment]
@raon0211 
I already tried it but it was still about 2x slower than lodash when the length of array > 10000.
