### ISSUE TITLE
Current bench implementation does not ensure that `es-toolkit` is always faster than `lodash`.

### ISSUE THREAD

**Issue by changwoolab** [toss/es-toolkit#57]
I think implementation for bench should cover various length of array to ensure that it is always faster than `lodash`

### Example

With current implementation, `intersection` is faster than lodash.

<img width="801" alt="Screenshot 2024-06-15 at 2 49 14 PM" src="https://github.com/toss/es-toolkit/assets/64240134/f5b028fe-86f9-4e7f-adf3-30c466f3f90b">

But after I just changed the length to 10000, `intersection` is slower than lodash
```ts
const array1 = Array.from({ length: 10000 }, () => Math.floor(Math.random() * 1000));
const array2 = Array.from({ length: 10000 }, () => Math.floor(Math.random() * 1000));

describe('intersection', () => {
  bench('es-toolkit', () => {
    intersectionToolkit(array1, array2);
  });

  bench('lodash', () => {
    intersectionLodash(array1, array2);
  });
});
```

<img width="787" alt="Screenshot 2024-06-15 at 2 48 27 PM" src="https://github.com/toss/es-toolkit/assets/64240134/8851aa83-6302-4019-827f-e5c702559225">

**Comment by raon0211** [comment]
Thanks for pointing this out :)

As you mentioned, there were some functions that are less performant than lodash when the array becomes large. We aim to optimize this by reducing time complexity.

When it comes to intersection and intersectionBy, it was actually improved in the following pull requests:

- [intersection](https://github.com/toss/es-toolkit/pull/47)
- [intersectionBy](https://github.com/toss/es-toolkit/pull/44)

Could you pull the latest version and check whether our implementation got faster?

**Comment by raon0211** [comment]
Seems that our implementation is still slow, even after optimizing our implementation -- we should add a test case and ensure that our implementation is faster in most cases.

**Comment by raon0211** [comment]
It's kind of strange in my environment that the result changes every time I re-run the test. 

Maybe the array is randomly created?

<img width="680" alt="image" src="https://github.com/toss/es-toolkit/assets/3102175/843656b0-5a7c-4853-9f65-71749878d8cf">

**Comment by raon0211** [comment]
Our aim is to be faster, or at least as fast as lodash most of the time.

**Comment by changwoolab** [comment]
@raon0211 
## Strange symptoms

It was tested on `v1.3.0` which includes PRs you mentioned.
I am so curious why in `intersection` and `uniqBy`, `es-toolkit` is always slower than lodash in my environment with large array. (about 1.7x)

But when I change the range from `1000` to `10000`, it became faster than lodash
```ts
import { randomInt } from 'crypto';
const array2 = Array.from({ length: 10000 }, () => randomInt(0, 10000));
```

But after I changed it into this, it became 2x slower than lodash 
```ts
import { randomInt } from 'crypto';
const array2 = Array.from({ length: 10000 }, () => randomInt(0, 1000)); // Changed range ~10000 to ~1000
```

## Deterministic test

To make the test determinant, you may use the implementation below. In my environment, lodash was 1.3x faster.
If you change the `array2`'s length smaller, the performance gap becomes more dramatic.
```tsx
const array1 = Array.from({ length: 10000 }, (_, idx) => idx);
const array2 = Array.from({ length: 10000 }, (_, idx) => idx);
```
<img width="801" alt="Screenshot 2024-06-15 at 5 34 12 PM" src="https://github.com/toss/es-toolkit/assets/64240134/b5f1ebc0-8436-43e1-a7b5-bdcfaaeff285">

## A little possible Improvement
(Below is my hypothesis, not thoroughly tested)
Current implementation is `O(N + M)` where N is array1's length and M is array2's length.
But because `new Set(Larger_Array)` leads to more memory allocation and less cache efficiency, it would be a little less performant if we use larger array for `Set`.
So it could be "slightly" improved by using `Set` with smaller array.

```ts
export function intersection<T>(firstArr: readonly T[], secondArr: readonly T[]): T[] {
  const [largerArray, smallerArray] = distinguishLargerOrSmallerArray(firstArr, secondArr);
  const secondSet = new Set(smallerArray);

  return largerArray.filter(item => {
    return secondSet.has(item);
  });
}

function distinguishLargerOrSmallerArray<T>(arr1: readonly T[], arr2: readonly T[]) {
  return arr1.length > arr2.length ? [arr1, arr2] : [arr2, arr1];
}
```

### Before
avg 1600
<img width="790" alt="Screenshot 2024-06-15 at 6 12 57 PM" src="https://github.com/toss/es-toolkit/assets/64240134/eed3bfcb-53b3-40ef-90f8-bac2f4acf1c7">

### After
avg 4500
<img width="804" alt="Screenshot 2024-06-15 at 6 13 50 PM" src="https://github.com/toss/es-toolkit/assets/64240134/483e4246-317f-45f0-b67f-4fae78968b59">

To make it more dramatic, I made `array1`'s length to be 10 and `array2`'s length to be 10000.

**Comment by changwoolab** [comment]
My hypothesis was wrong, it doesn't work with random variables at all.
It works only if when I initialized array like this `const array1 = Array.from({ length: 100 }, (_, idx) => idx);`

**Comment by raon0211** [comment]
This is kind of strange, I think we should look into how lodash implemented `intersection`.

**Comment by changwoolab** [comment]
@raon0211 
Regarding to lodash's implementation, I reimplemented the function. Then it became much faster than lodash.
It is interesting that pure object is faster than `Set` when the size is big.

```ts
export function intersection<T>(firstArr: readonly T[], secondArr: readonly T[]): T[] {
  const map = Object.create(null);

  for (const item of secondArr) {
    map[item] = true;
  }

  const result = [];
  for (const item of firstArr) {
    if (map[item]) {
      result.push(item);
      map[item] = true;
    }
  }
  return result;
}
```

<img width="782" alt="Screenshot 2024-06-15 at 7 56 15 PM" src="https://github.com/toss/es-toolkit/assets/64240134/f4eff3d8-57e7-4e49-bb07-98a1cc07b79c">

**Comment by changwoolab** [comment]
But it is slower than current implementation when the size of array is small.

**Comment by changwoolab** [comment]
Maybe this could be an optimal implementation. I will test this thoroughly.
```ts
export function intersection<T>(firstArr: readonly T[], secondArr: readonly T[]): T[] {
  if (firstArr.length < 120) {
    return intersectionSmallArrays(firstArr, secondArr);
  }

  return intersectionLargeArrays(firstArr, secondArr);
}

function intersectionSmallArrays<T>(firstArr: readonly T[], secondArr: readonly T[]): T[] {
  const secondSet = new Set(secondArr);

  return firstArr.filter(item => {
    return secondSet.has(item);
  });
}

function intersectionLargeArrays<T>(firstArr: readonly T[], secondArr: readonly T[]): T[] {
  const map = Object.create(null);

  for (const item of secondArr) {
    map[item] = true;
  }

  const result = [];
  for (const item of firstArr) {
    if (map[item]) {
      result.push(item);
      map[item] = true;
    }
  }
  return result;
}
```

**Comment by changwoolab** [comment]
I found the ways to reproduce these

1. Occurs when operand's type is `number` and ranges `< 5000`.
Pure object was faster when dealing with numbers which are smaller than 5000 in my experiment. (What an edge case this is)

2. Occurs when `array1.length <= 50 && array2.length >= 5000`
Example
```ts
describe('intersection, large array with large numbers', () => {
  const array1 = Array.from({ length: 10 }, () => Math.floor(Math.random() * 1000000000 + 100000));
  const array2 = Array.from({ length: 5000 }, () => Math.floor(Math.random() * 1000000000 + 100000));

  bench('es-toolkit', () => {
    intersectionToolkit(array1, array2);
  });

  bench('lodash', () => {
    intersectionLodash(array1, array2);
  });
});
```

**Comment by raon0211** [comment]
I've been thinking about our priorities, and here's what I suggest our priorities are (from high to low):

1. Achieve the best performance for the major 85% of use cases.
2. Keep the implementation simple.
3. Aim for optimal performance in all use cases.

It seems that calculating intersections for small arrays is one of our main use cases, and I guess they occur 85% of the time, as we rarely deal with arrays larger than 10,000 elements. So, I think we should stick with the current implementation.

**Comment by changwoolab** [comment]
@raon0211 
I do agree with you.
I tried to optimize "all" use cases, but there were always edge cases where `lodash` was faster. If I find all of them and add conditional statements to make it faster than lodash, the implementation would be too dirty to maintain.
I think it is better to focus on general cases.

But in `intersection`, it would be better to use `Array.prototype.includes` to optimize when array is small because lodash is faster even though the size of array is small, which is our target general case.
But, in this case additional conditional statements need to be added which could lead to non-maintainable code.

You may try the code below
```ts
describe('intersection', () => {
  const array1 = Array.from({ length: 10 }, () => Math.floor(Math.random() * 1000));
  const array2 = Array.from({ length: 50 }, () => Math.floor(Math.random() * 1000));

  bench('es-toolkit', () => {
    intersectionToolkit(array1, array2);
  });

  bench('lodash', () => {
    intersectionLodash(array1, array2);
  });
});
```

![Screenshot 2024-06-20 at 1 10 00 PM](https://github.com/toss/es-toolkit/assets/64240134/38bff263-c93d-43b1-b2d7-82c663832110)

**Comment by raon0211** [comment]
I thought about adding an `if` statement in `intersection`. However, [implementation simplicity](https://github.com/toss/es-toolkit/blob/main/.github/CONTRIBUTING.md#12-simplicity) has one of the top priorities in our library. 

Adding a conditional statement will lead to added complexity, which is not we are aiming for. I wish we stick with the current implementation, and not add a conditional statement.
