### ISSUE TITLE
Support for typed `Object.entries`

### ISSUE THREAD

**Issue by ho991217** [toss/es-toolkit#58]
The `omitBy` and `pickBy` function have implemented like this:
```ts
const result: Partial<T> = {};

for (const [key, value] of Object.entries(obj)) {
  if (shouldOmit(value, key)) { // or if(!shouldPick(value, key)) {
    continue;
  }

  (result as any)[key] = value;
}
```
The problem is, typescript does not know if the `key` from `Object.entries(obj)` is part of the `obj`'s key. So `result` had to be asserted as `any` even though it was declared at the top, which is less _type-safe_. Also, the `value` is inferred as `any` type, too.

Adding type assertion to `Object.entries(obj)` might be helpful. And changing type of `key` from `string` to `keyof T`. I want to know whether you intentionally set type of `key` to `string` instead of `keyof T` or not.

If you want to utilize typed `Object.entries` more, please consider adding `toPairs` function which implemented in [lodash](https://lodash.com/docs/4.17.15#toPairs).

Let me know what you think!

**Comment by ho991217** [comment]
If you think this is fair enough, may I work on this one?

**Comment by raon0211** [comment]
Thank you for your helpful suggestion!

Our `es-toolkit` library focuses on utilities that are useful during runtime, not for static types. With this in mind, I believe functions like `toPairs` which only improve types might not be a good fit for our library.

The best solution might be to improve the types provided by TypeScript itself...

**Comment by ho991217** [comment]
Understood. But is there any reason for `key: string` instead of `key: keyof T`?

**Comment by raon0211** [comment]
I guess we should change the types of `key` in `shouldOmit` to `keyof T`.

**Comment by ho991217** [comment]
`!shouldPick` in `pickBy` either! May I take this one?

**Comment by raon0211** [comment]
Of course!
