### ISSUE TITLE
startCase wrong behaviour/s

### ISSUE THREAD

**Issue by damianobarbati** [toss/es-toolkit#580]
`startCase` is not working properly when an uppercase string is provided, you have to `toLowerCase` it first.

Also, it's removing commas. 

Is this the intended behaviour?

**Comment by dayongkr** [comment]
I think this issue arose while referencing the implementation of lodash. As you can see [here](https://github.com/lodash/lodash/pull/908#issuecomment-72353907), lodash has the same problem, but it seems they haven’t fixed it for the sake of implementation convenience. The same goes for the comma issue.

In my opinion, it is correct to fix the first problem(Uppercase issue).

**Comment by raon0211** [comment]
This is very strange. Although our compat library might match lodash's behavior, I guess we should fix this in our original library..

**Comment by hyesungoh** [comment]
I uppercase issue at #591 👍 

I wonder what you think about the comma issue 🤔

**Comment by raon0211** [comment]
I think our library should not remove commas from the original string.

**Comment by damianobarbati** [comment]
@raon0211 sorry to bother, I see also this other behaviour: with accented letters, the accented letter is prefixed with a space and is turned uppercase.
Eg:
`lunedì 18 set` => `Luned Ì 30 Set`

**Comment by raon0211** [comment]
Let me fix this.

**Comment by raon0211** [comment]
https://github.com/toss/es-toolkit/commit/a5e3b49d8a92125e97121a0036723e53e177350e

It was fixed in this commit. Will be fixed in the next release.

**Comment by damianobarbati** [comment]
Wow this wast fast. I'll wait the scheduled release, thank you!
