### ISSUE TITLE
[request] get(obj, '.'): return root

### ISSUE THREAD

**Issue by mustafa0x** [toss/es-toolkit#605]
i expected `get(obj, '.')` to behave like jq and return the root object. it seems that isn't the case.

i think this would be a nice to have. im not sure if es-toolkit is maintaining exact alignment with lodash behavior though.

**Comment by raon0211** [comment]
Hello, thanks for your suggestion. 

Currently, `es-toolkit/compat` aims for perfect compatibility with lodash. It seems that `lodash` is not returning root for `get(obj, '.')`, so currently it is out of scope of our library.
