### ISSUE TITLE
Type unity of `debounce`

### ISSUE THREAD

**Issue by sossost** [toss/es-toolkit#61]
```typescript
 39 export function debounce<F extends (...args: any[]) => void>(
 ...
 ...
 46 const debounced = function (...args: Parameters<F>) {
 ```
 
 Hi, the type of the (...args) argument of the `debounce` function is defined as `Parameters<F>` below, but as `any[]`  above. Is there any other reason for this?

**Comment by jungwoo3490** [comment]
@sossost
The reason for the parameter type of the `debounced` function is to ensure that it has the same parameter types as the original func function.

**Comment by sossost** [comment]
@jungwoo3490
Oh, what an idiot I was!

I had implemented the debounce function using Prameters<F> instead of ...any[], and I realized that 
Now that I think about it, I realize that this creates a circular reference to F.

I'll close this issue, thanks.
