### ISSUE TITLE
merge can mutate source

### ISSUE THREAD

**Issue by Xiot** [toss/es-toolkit#623]
I found some unexpected behaviour with the `merge` function.

It appears that when values are merged, there are cases where it just copies the reference to the source object.

```javascript
const target = {}
const source = { a: { b: 1 } }
const m = merge(target, source)
console.log('merged', m)
console.log('target', target)
console.log('source', source)

m.a.c = 2
console.log('merged', m)
console.log('target', target)
console.log('source', source)
```

which produces
```
merged { a: { b: 1 } }
target { a: { b: 1 } }
source { a: { b: 1 } }
merged { a: { b: 1, c: 2 } }
target { a: { b: 1, c: 2 } }
source { a: { b: 1, c: 2 } }  // expected `source` to not have changed
```

This seems to be what is responsible
https://github.com/toss/es-toolkit/blob/main/src/object/merge.ts#L98

The same code using the `merge` method from lodash produces
```
merged { a: { b: 1 } }
target { a: { b: 1 } }
source { a: { b: 1 } }
merged { a: { b: 1, c: 2 } }
target { a: { b: 1, c: 2 } }
source { a: { b: 1 } }
```

At least in my eyes, the one from `lodash` seems more correct, since the `source` is never mutated.  
Curious to hear your thoughts on if this is intentional, and if so, what is the reasoning.

**Comment by Xiot** [comment]
Just noticed that there is a PR that addresses this https://github.com/toss/es-toolkit/pull/556

**Comment by raon0211** [comment]
Hello, thanks for your report. We merged the pull request. https://github.com/toss/es-toolkit/blob/main/src/object/merge.ts#L98

Can you check if `es-toolkit@1.22.0-dev.706` works for you?

**Comment by Xiot** [comment]
`es-toolkit@1.22.0-dev.706` seems to fix the issue.

Thanks
