### ISSUE TITLE
Array.prototype.at version compatibility 

### ISSUE THREAD

**Issue by ssi02014** [toss/es-toolkit#665]
The `es-toolkit` internal at function seems to use `Array.prototype.at`, which is a newer specification and I thought it might cause version compatibility issues. (ex. `ios v15`)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility

Why not add a function like [nth](https://lodash.com/docs/4.17.15#nth) from `lodash` to utilize it?

I'm just commenting because it doesn't seem to be polyfilling at build time.

```ts
// dist/array/at.mjs
function at(arr, indices) {
    const result = [];
    for (let i = 0; i < indices.length; i++) {
        const index = indices[i];
        result[i] = arr.at(index);
    }
    return result;
}

export { at };
```

### Suggestion
```ts
export function nth<T>(
  arr: readonly T[],
  index: number = 0
): T | undefined {
  const len = arr.length;
  const relativeIndex = index < 0 ? len + index : index;

  if (relativeIndex < 0 || relativeIndex >= len) {
    return undefined;
  }

  return arr[relativeIndex];
}
```

**Comment by raon0211** [comment]
Actually this is intended behavior to use native APIs as much as possible, as long as it is supported in the oldest LTS version of Node.js. 

If needed, you might include polyfills to your app.

**Comment by ssi02014** [comment]
@raon0211 Thanks for your feedback :)
