### ISSUE TITLE
Performance Improvement for `randomInt`

### ISSUE THREAD

**Issue by kms0219kms** [toss/es-toolkit#69]
현재는 randomInt가 내부적으로는 Math.floor로 random 함수를 워핑하는 것 같습니다.

다만, Math.floor가 비트연산자 `| 0` 내지는 `~~`로 소숫점 이하를 버리는 것과 결과가 대개(Infinity나 NaN, 음수를 넣었을 때의 결과 제외) 똑같고,
비트연산자 혹은 `~~`을 사용하는 것이 퍼포먼스 측면에서 더우 빠르다는 점이 널리 알려져있습니다.

따라서 Math.floor 대신 비트연산자 `| 0`, 내지 `~~`와 같은 방법으로 대체하실 의향은 없으신지 의견드립니다. (비록, 안정성 측면에서 깊은 고려가 필요할겁니다.)

참고 : `~~`는 32-bit 숫자에서 performance issue가 있는 것 같습니다.

Currently it seems that randomInt internally warps the random function to Math.floor.

However, Math.floor is a bitwise operator | The result is usually the same as discarding decimal places with 0 or ~~ (excluding the results when Infinity, NaN, or negative numbers are entered),
It is widely known that using bitwise operators or ~~ is faster in terms of performance.

Therefore, instead of Math.floor, we use the bitwise operator | I would like to ask if you are willing to replace it with 0, to ~~. (Although, deep consideration will be needed in terms of stability.)

Note: ~~ seems to have a performance issue with 32-bit numbers.

**Comment by kms0219kms** [comment]
<img width="961" alt="Screenshot 2024-06-16 at 5 53 37 PM" src="https://github.com/toss/es-toolkit/assets/67222970/dc4221e8-31de-4882-aff6-69d13971f404">

벤치마크는 [https://jsperf.app/pugihi](https://jsperf.app/pugihi) 에서 확인 가능합니다.

**Comment by sossost** [comment]
Personally, I think a consistent and readable Math.floor is what the library is for, if not for the performance benefits. 
Also, it behaves differently with negative numbers than it does with positive numbers.
What do you think?

**Comment by kms0219kms** [comment]
@sossost , 사실 랜덤은 보통 양수에서 많이 발생하고 음수에서는 잘 일어나지 않습니다. Math.random()도 음수를 지원하진 않아서, 야매로 작업해야 합니다.

이 라이브러리는 속도와 안정성 두가지 모두 중요시 하는 라이브러리이기 때문에, 이 방식으로의 전환은 조금 조심해야 한다는 부분에서는 동의합니다만, 본 이슈를 통해 본 라이브러리가 중요시 하는 부분 등을 전체적으로 확인할 수 있는 계기가 되면 좋겠습니다.

**Comment by sossost** [comment]
Personally, I think Math.floor is better suited to the principles of implementation simplicity that this library stands for in terms of consistency and readability, unless the performance benefits are significant enough.
Also, the double tilde operator behaves differently for positive and negative numbers.
What do you think?

**Comment by sossost** [comment]
@kms0219kms However, the random function supports negative ranges and will generate random numbers in the range above minimum (inclusive) and below maximum (exclusive).
So for consistency in implementation, math.floor seems to be better suited for the simplicity case.
It's a question of performance benefits versus simplicity of implementation.

**Comment by raon0211** [comment]
In my opinion, we should consider using bitwise operators only if there's a significant performance improvement.

However, based on the information provided by @kms0219kms ([link](https://github.com/toss/es-toolkit/issues/69#issuecomment-2171431107)), the performance difference doesn't seem substantial enough to justify the loss of readability.

For now, I suggest we prioritize simplicity in our implementation.

**Comment by kms0219kms** [comment]
> In my opinion, we should consider using bitwise operators only if there's a significant performance improvement.
> 
> 
> 
> However, based on the information provided by @kms0219kms ([link](https://github.com/toss/es-toolkit/issues/69#issuecomment-2171431107)), the performance difference doesn't seem substantial enough to justify the loss of readability.
> 
> 
> 
> For now, I suggest we prioritize simplicity in our implementation.
> 
> 

네, 현재 비트연산으로의 floor처리는 일반적인 PC환경에서는 성능차이가 존재하나 유의미한 정도로 크진 않습니다.

모바일에서는 3~5% 정도 속도가 빠른 유의미한 결과가 나오긴합니다만, 가독성과 안정성 손실을 정당화할 만큼 유의미하진 않다는 의견에는 동의합니다.

앞으로 나아갈 방향이 이미 명확하게 결정된 것으로 보이므로 이슈를 마무리하겠습니다.

Yes, there is a performance difference in the floor using current bit operations in a general PC, but it is insignificant.

On mobile, there are meaningful results about 3-5% faster, but I agree that it is not significant enough to justify the loss of readability and stability.

I would close this issue as the pathway forward has already been clearly decided.
