### ISSUE TITLE
Support for `toSafeInteger`

### ISSUE THREAD

**Issue by chhw130** [toss/es-toolkit#690]
I will implement this and open a PR.

But, I couldn't find test cases from [lodash](https://github.com/lodash/lodash/tree/afcd5bc1e8801867c31a17566e0e0edebb083d0e/test).

**Comment by D-Sketon** [comment]
https://github.com/lodash/lodash/blob/v5-wip/test%2FtoInteger-methods.spec.js

**Comment by chhw130** [comment]
> https://github.com/lodash/lodash/blob/v5-wip/test%2FtoInteger-methods.spec.js

Thank you so much for your kindness!
