### ISSUE TITLE
Support for `sample`

### ISSUE THREAD

**Issue by Gyumong** [toss/es-toolkit#699]
Hello, @raon0211 
I’d like to contribute by working on the sample function if it’s available.

Currently, the `sample` function in es-toolkit only supports arrays. To improve compatibility with Lodash and enhance its functionality, I propose the following updates

1. Add support for object sampling
2. Handle empty collections
3. Handle `null` or `undefined` inputs

**Comment by Gyumong** [comment]
I plan to ensure that only compat support objects

**Comment by D-Sketon** [comment]
lodash also support arraylike
for example _.sample('123') is legal

**Comment by Gyumong** [comment]
Thank you for your helpful feedback :)

**Comment by raon0211** [comment]
Great work. Thanks!
