### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by stijns96** [toss/es-toolkit#717]
Hi there,

I just installed this module with `pnpm` and tried to use the `debounce` util. While doing this, I'm getting the following error (Rollup):

`Circular dependency: node_modules/.pnpm/es-toolkit@1.25.1/node_modules/es-toolkit/dist/predicate/isJSONArray.mjs -> node_modules/.pnpm/es-toolkit@1.25.1/node_modules/es-toolkit/dist/predicate/isJSONValue.mjs -> node_modules/.pnpm/es-toolkit@1.25.1/node_modules/es-toolkit/dist/predicate/isJSONArray.mjs`

I could hide this error with a rollup setting, but I'm wondering if this is something you're aware of?

I'm now using 1.22.0 since that one doesn't support isJSONArray yet. So no warnings.

**Comment by raon0211** [comment]
We resolved this issue in [this commit](https://github.com/toss/es-toolkit/commit/904ca1a2b46b8d5046a6abc550c739ebd41eff4f) and released a new version v1.25.2. Could you give it a try?

**Comment by stijns96** [comment]
Hi @raon0211,

Fixed indeed! Thanks for the really quick fix!
