### ISSUE TITLE
[Bug]: find Error, value null always find first

### ISSUE THREAD

**Issue by roytan883** [toss/es-toolkit#750]
```
// "es-toolkit": "1.25.2"

const items = [
  { id: 1, name: 'Alice' },
  { id: 2, name: 'Bob' },
];
const result = find(items, { name: null });
console.log(`result:`, result);
// result: { id: 1, name: 'Alice' }
```
why `name: null` find `name: 'Alice'` ?

**Comment by D-Sketon** [comment]
It looks like `isMatch` only considers the case where the value is undefined and ignores null

**Comment by roytan883** [comment]
> It looks like `isMatch` only considers the case where the value is undefined and ignores null

Does that mean `null` can match anything? 
It is fundamental. The whole project will be unstable and useless, if this bug exists. 
I can't believe it.

**Comment by D-Sketon** [comment]
we will fix it

**Comment by raon0211** [comment]
Can you check with the latest version, v1.26.1?

**Comment by roytan883** [comment]
> Can you check with the latest version, v1.26.1?

Confirmed, v1.26.1 fixed this bug.

**Comment by roytan883** [comment]
@D-Sketon @raon0211 

After this bug fix, i still don't know why `expect(isMatch({ a: 1 }, null)).toBe(true);`
But `lodash` also have this problem:
when second argument is null, always return first element.

Why `{ id: 1, name: 'Alice' }` can match `null`, still don't get it.
Then i create my own fixing version of find().

```
// lodash
import {find as findLd} from "lodash-es"
const items = [
  { id: 1, name: 'Alice' },
  { id: 2, name: 'Bob' },
];
let result = findLd(items, null);
console.log(`result:`, result); //result: { id: 1, name: 'Alice' }

// es-toolkit
import {find as findTk} from "es-toolkit/compat"
const items = [
  { id: 1, name: 'Alice' },
  { id: 2, name: 'Bob' },
];
let result = findTk(items, null);
console.log(`result:`, result); //result: { id: 1, name: 'Alice' }

// my fix
function find(array, predicate) {
  if (predicate === null || predicate === undefined) {
    return undefined
  }
  return findTk(array, predicate)
}
```

It is a lodash bug or designed like this?

**Comment by D-Sketon** [comment]
While I was fixing it, I did notice something strange about the lodash implementation.

In fact, the following statements are all true in lodash
```ts
_isMatch({a:1})
_isMatch({a:1},1)
_isMatch({a:1},true)
_isMatch({a:1},null)
_isMatch({a:1},()=>{})
_isMatch({a:1},{})
```

**Comment by roytan883** [comment]
So do i.
`isMatch` behaviour is strange.
