### ISSUE TITLE
Why is there no is_empty method?

### ISSUE THREAD

**Issue by chenbimo** [toss/es-toolkit#756]
This is a great project and I use it every day. However, I have been paying attention for a long time, and the is_empty method in Lodash has not been implemented. Is there any plan to implement this function? Thank you very much for your work!

**Comment by raon0211** [comment]
It will be included in the next version of our library :)

https://es-toolkit.slash.page/reference/compat/predicate/isEmpty.html

**Comment by chenbimo** [comment]
> It will be included in the next version of our library :)
> 
> https://es-toolkit.slash.page/reference/compat/predicate/isEmpty.html

Cool!

**Comment by TiBianMod** [comment]
related https://github.com/toss/es-toolkit/issues/298

**Comment by raon0211** [comment]
This was fixed in es-toolkit v1.27.0 :)
