### ISSUE TITLE
Support for `sum` and `sumBy` in compat layer

### ISSUE THREAD

**Issue by dayongkr** [toss/es-toolkit#757]
It will help for solving this #742 .

**Comment by raon0211** [comment]
Actually, I think we should support `bigint`s in our original library. There is no easy way to handle them in native JavaScript. What do you think?

Of course, we need compatibility layers for `sum` and `sumBy`, too...

**Comment by dayongkr** [comment]
> Actually, I think we should support `bigint`s in our original library. There is no easy way to handle them in native JavaScript. What do you think?
> 
> Of course, we need compatibility layers for `sum` and `sumBy`, too...

I am not adding new functionality to Lodash.

Although handling of `bigInt` arrays is not explicitly mentioned in Lodash’s test cases, it is already supported due to the way its internal implementation works.

**Comment by dayongkr** [comment]
If it’s about performing calculations with a mix of `number` and `bigInt`, I also agree that it would be better to add this functionality to the original library.

**Comment by raon0211** [comment]
Actually, we intentionally don't mix numbers and bigints in JavaScript; for example, `0 + 1n` throws. So we should exclusively handle arrays which have only numbers or only bigints. 

I thought handling `bigint` arrays in the original `sum` function was needed...

**Comment by dayongkr** [comment]
> Actually, we intentionally don't mix numbers and bigints in JavaScript; for example, `0 + 1n` throws. So we should exclusively handle arrays which have only numbers or only bigints.
> 
> I thought handling `bigint` arrays in the original `sum` function was needed...

It seems like I misunderstood the intention of the question. If you’re asking whether this feature is needed in our original library, I agree.

For now, I’ll implement the compatibility version, and if no one else attempts to implement it in original version, I’ll try adding it to the original library myself.

**Comment by dayongkr** [comment]
> Actually, we intentionally don't mix numbers and bigints in JavaScript; for example, `0 + 1n` throws. So we should exclusively handle arrays which have only numbers or only bigints.
> 
> I thought handling `bigint` arrays in the original `sum` function was needed...

I momentarily overlooked that it was big`int`. So, I thought you were simply asking for a feature to perform typecasting and calculations, but I made a brief mistake.
