### ISSUE TITLE
Type definitions are same for intersectionWith, differenceWith, etc

### ISSUE THREAD

**Issue by warapitiya** [toss/es-toolkit#819]
I have noticed that the type definitions of `intersectionWith`, `intersectionBy`, `differenceWith`, and `differenceBy` are the same, and they access the same type of arrays.

```ts
import { intersectionWith } from "es-toolkit";

type CSV = { id: number; csv: number };
type JSON = { id: number; json: number };

const array1: CSV[] = [
  { id: 1, csv: 1 },
  { id: 2, csv: 1 },
  { id: 3, csv: 1 },
];
const array2: JSON[] = [
  { id: 2, json: 2 },
  { id: 4, json: 2 },
];

const result = intersectionWith(array1, array2, (a, b) => a.id === b.id);
                                          ^
                                          |
                                          |
                                          |
// Argument of type 'JSON[]' is not assignable to parameter of type 'readonly CSV[]'.
// Property 'csv' is missing in type 'JSON' but required in type 'CSV'.
```

https://github.com/toss/es-toolkit/blob/aac6974e35961fb21ff5bc133e7d3f7b8199ea89/src/array/intersectionWith.ts#L23-L33

This occurs primarily because `secondArr` accepts the same type as `firstArr`. Is this intentional? It feels like a bug, particularly because we only return the values of `firstArr` if `areItemsEqual` returns true.

**Comment by warapitiya** [comment]
I am sharing a comparison with `lodash-es` here.

[> codesandbox](https://codesandbox.io/p/sandbox/gt6f6k)

**Comment by raon0211** [comment]
Yeah, seems that this is a problem. Will fix this in the next release.
