### ISSUE TITLE
Support for `sortBy`

### ISSUE THREAD

**Issue by raon0211** [toss/es-toolkit#85]
Support for [sortBy](https://lodash.com/docs/4.17.15#sortBy) is needed.

**Comment by l2hyunwoo** [comment]
🙋‍♂️

**Comment by raon0211** [comment]
Thanks!

**Comment by dayongkr** [comment]
If this issue is not working on, then can I works it?

**Comment by raon0211** [comment]
@dayongkr Sure!

**Comment by dayongkr** [comment]
Ok, I am going to check this function!
