### ISSUE TITLE
Support for `sampleSize`

### ISSUE THREAD

**Issue by raon0211** [toss/es-toolkit#87]
Support for [sampleSize](https://lodash.com/docs/4.17.15#sampleSize) is needed.

**Comment by jgjgill** [comment]
I've tried writing the code as follows.

```ts
import { clamp, random } from '../math';

export function sampleSize<T>(array: readonly T[], size: number): T[] {
  const arr = [...array];
  const clampSize = clamp(size, arr.length);

  let index = 0;

  while (index < clampSize) {
    const randomNumber = Math.floor(random(index, arr.length));
    const value = arr[randomNumber];

    arr[randomNumber] = arr[index];
    arr[index] = value;

    index += 1;
  }

  arr.length = clampSize;

  return arr;
}
```

If this direction is okay, is it okay for me to move forward with testing and documentation?

**Comment by raon0211** [comment]
Hello, thanks for sharing your implementation. What about reusing [sample](https://es-toolkit.slash.page/reference/array/sample.html#sample) from our library?

```tsx
function sampleSize(arr, size) {
  const length = clamp(size, 0, arr.length);

  return Array.from({ length }).map(() => sample(arr));
```

I guess this implementation is quite straightforward, but we have to test whether this implementation is actually performant.

**Comment by jgjgill** [comment]
Oh, thank you for your quick feedback! 😆
I also tried to use 'sample' at first, but I'm having issues with duplicate results.

```ts
sampleSize([1, 2, 3], 3); // [1, 1, 1] 🤔
```

So, like `lodash`, I wanted to increment the index position and exclude duplicates.
If you don't mind getting duplicate results, I'll process with the work reusing `sample`!

**Comment by raon0211** [comment]
Yes, you are correct; `sampleSize` should not return duplicate values.

Researching how to do this correctly, I actually found out [this algorithm](https://www.nowherenearithaca.com/2013/05/robert-floyds-tiny-and-beautiful.html):

```tsx
/**
 * @see Floyd's algorithm. http://stackoverflow.com/questions/2394246/algorithm-to-select-a-single-random-combination-of-values
 */
function sampleSize(array, size) {
  const result = new Array(size);
  const selected = new Set();

  for (let step = array.length - size, resultIndex = 0; step < array.length; step++, resultIndex++) {
    let index = randomInt(0, step);

    if (selected.has(index)) {
      index = step;
    }

    selected.add(index);

    result[resultIndex] = array[index];
  }

  return result;
}
```

What about trying this algorithm?

**Comment by jgjgill** [comment]
I didn't know this algorithm. Thanks for letting me know. 🙇‍♂️

However, as I understand the algorithm, I'm having the following problem. 🧐

### Example

**randomInt maximum exclusive**

```ts
function sampleSize([1, 2, 3], 2) {
  ...
  for (let step = 3 - 2, ... // array.length - size
    let index = randomInt(0, 1) // always start 0, exclude 1, 2
    ...

    result[resultIndex] = array[index];
  }

  return result; // [1, 2] or [1, 3]; always include 1
}
```

**randomInt maximum inclusive**

```ts
function sampleSize([1, 2, 3], 2) {
  ...
  for (let step = 3 - 2, ... // array.length - size
    let index = randomInt(0, 1) // always start 0, 1 exclude 2; I think it's not random
    ...

    result[resultIndex] = array[index];
  }

  return result; // [0, ?] or [1, ?]
}
```

**`size` === `array.length`**

```ts
function sampleSize([1, 2, 3], 3) {
  ...
  for (let step = 3 - 3, ... // array.length - size
    let index = randomInt(0, step) // Step is always 0, 1, 2; Index is always 0, 1, 2
    ...

    result[resultIndex] = array[index];
  }

  return result; // always return [1, 2, 3]; It's not random
}
```
This is not the purpose of `sample`.
I think [the stackflow](https://stackoverflow.com/a/2394808) you shared says something similar.

### Fisher–Yates shuffle

> The Fisher-Yates Shuffle randomly permutes a list by iteratively swapping each element with a randomly selected element from the unshuffled portion.

I understood that if you want to use randomization here, you use `Fisher-Yates shuffle`.

This is included in the original suggestion code.
(I learned about it while studying this time, sorry I didn't leave a detailed explanation at the beginning 😂)

I think I learned a lot this time, thanks.

**Comment by raon0211** [comment]
Actually, I believe the algorithm is correct for the "maximum inclusive" case.

When using `sampleSize([1, 2, 3], 2)`, note that we can only select from `[1, 2]`, `[1, 3]`, and `[2, 3]`. Therefore, it is correct that either `[1, ?]` or `[2, ?]` will be chosen.

As you mentioned, this algorithm returns the original array when `size === array.length`, i.e., `sampleSize([1, 2, 3], 3)`. However, this behavior is also correct because `[1, 2, 3]` is the only selection possible in this case.

Unlike lodash, I understand that the indices are not shuffled. However, the main purpose of `sampleSize` is to select a sample from an array, not to shuffle indices.

**Comment by jgjgill** [comment]
I understand what you said!
I'm going to get to work and write a PR.

Probably [randomInt](https://github.dev/toss/es-toolkit/blob/ad683b82c7d71a975544d0445b83c9dbdb54b5d5/src/math/randomInt.ts#L9-L10) is currently maximum exclusive, so I'll fix that in the code you suggested.

Thanks a lot for your help. 🙇‍♂️

**Comment by raon0211** [comment]
Yes! If possible, we might just use `randomInt(0, step + 1)`...
