### ISSUE TITLE
Would it be possible to add the sleep function?

### ISSUE THREAD

**Issue by drag0n-app** [toss/es-toolkit#870]
Reference radash function
https://radash-docs.vercel.app/docs/async/sleep

source code
```
/**
 * Async wait
 */
export const sleep = (milliseconds: number) => {
  return new Promise(res => setTimeout(res, milliseconds))
}
```

**Comment by Smrtnyk** [comment]
I found myself needing this many times
mostly while debugging some stuff though, but still needed it

**Comment by mass2527** [comment]
Doesn’t the [delay](https://es-toolkit.slash.page/reference/promise/delay.html#delay) function meet your needs?
