### ISSUE TITLE
Support for `fill`

### ISSUE THREAD

**Issue by raon0211** [toss/es-toolkit#94]
We need to support [fill](https://lodash.com/docs/4.17.15#fill).

**Comment by hansolbangul** [comment]
I've given this a try:

```typescript
export function fill<T>(array: any[], value: T): T[];
export function fill<T, P>(array: Array<T | P>, value: P, start?: number, end?: number): Array<T | P>;
export function fill<T, P>(array: Array<T | P>, value: P, start = 0, end?: number): Array<T | P> {
  if (array == null) {
    return [];
  }

  const length = array.length;
  if (!length) {
    return array;
  }

  const startIdx = start < 0 ? Math.max(length + start, 0) : Math.min(start, length);
  const endIdx = end === undefined ? length : end < 0 ? Math.max(length + end, 0) : Math.min(end, length);

  for (let i = startIdx; i < endIdx; i++) {
    array[i] = value;
  }

  return array;
}

```

If the above code looks good, may I proceed with enhancing the documentation and tests, and then submit a pull request?

**Comment by raon0211** [comment]
```tsx
export function fill<T>(array: unknown[], value: T): T[];
export function fill<T, P>(array: Array<T>, value: P, start: number): Array<T | P>;
export function fill<T, P>(array: Array<T>, value: P, start: number, end: number): Array<T | P>;
export function fill<T, P>(array: Array<T>, value: P, start = 0, end = array.length): Array<T | P> {
  start = Math.max(start, 0);
  end = Math.min(end, array.length);

  for (let i = start; i < end; i++) {
    array[i] = value;
  }

  return array;
}
```

What about implementation like this? I guess it is more simpler.

**Comment by hansolbangul** [comment]
> ```tsx
> export function fill<T>(array: unknown[], value: T): T[];
> export function fill<T, P>(array: Array<T>, value: P, start: number): Array<T | P>;
> export function fill<T, P>(array: Array<T>, value: P, start: number, end: number): Array<T | P>;
> export function fill<T, P>(array: Array<T>, value: P, start = 0, end = array.length): Array<T | P> {
>   start = Math.max(start, 0);
>   end = Math.min(end, array.length);
> 
>   for (let i = start; i < end; i++) {
>     array[i] = value;
>   }
> 
>   return array;
> }
> ```
> 
> What about implementation like this? I guess it is more simpler.

Your code is excellent. I've learned something new!
