### ISSUE TITLE
Support for `head`, `tail`, `initial`, and `last`

### ISSUE THREAD

**Issue by raon0211** [toss/es-toolkit#95]
We need to support the following four functions.

- [ ] [head](https://lodash.com/docs/4.17.15#head)
- [ ] [tail](https://lodash.com/docs/4.17.15#tail)
- [ ] [initial](https://lodash.com/docs/4.17.15#initial)
- [ ] [last](https://lodash.com/docs/4.17.15#last)

**Comment by raon0211** [comment]
Sure!

**Comment by minchodang** [comment]
hello @hautest? 
First, I'm sorry I had to ask the original author on this issue and work on it. (Sorry, I should have asked about the head function before and worked on it)

By any chance, did you work on the initial function? If you haven't, I'd like to create a new issue and work on it. I'm curious to know if you're working on it.(cc. @raon0211)

**Comment by hautest** [comment]
@minchodang  hello minchodang

Sure, you can work on it :)

**Comment by minchodang** [comment]
hello @hautest. 
Thank you so much for your consideration.
i work on it. (cc. @raon0211)
i will reissue #151 @raon0211.
