### ISSUE TITLE
Support for `inRange`

### ISSUE THREAD

**Issue by raon0211** [toss/es-toolkit#97]
Support for [inRange](https://lodash.com/docs/4.17.15#inRange) is needed.

**Comment by jgjgill** [comment]
I think of it like this. 🧐

```ts
import { isNil } from 'lodash';

export function inRange(value: number, end: number): boolean;
export function inRange(value: number, start: number, end: number): boolean;
export function inRange(value: number, start: number, end?: number): boolean {
  if (isNil(end)) {
    end = start;
    start = 0;
  }

  return Math.min(start, end) <= value && value < Math.max(start, end);
}

```

- support negative ranges
- start inclusive, end exclusive

I did a quick test now and it passed.

<img width="457" alt="스크린샷 2024-06-30 오후 2 50 13" src="https://github.com/toss/es-toolkit/assets/79239852/5de2159c-ffef-47bc-b1f5-514ef228e592">

If that's okay, I'll work on it.

**Comment by raon0211** [comment]
```tsx
export function inRange(value: number, maximum: number): boolean;
export function inRange(value: number, minimum: number, maximum: number): boolean;
export function inRange(value: number, minimum: number, maximum?: number): boolean {
  if (maximum == null) {
    maximum = minimum;
    minimum = 0;
  }

  if (start >= end) {
    throw new Error('The maximum value must be greater than the minimum value.');
  }

  return start <= value && value < end;
}
```

What about writing the code like this? 

I think we should throw an error when minimum is greater than maximum. Also, I wish we don't have to add a extra function call unless we have some reasons (like code readability or TypeScript type guards..)

**Comment by jgjgill** [comment]
Oh, I think the code you suggested is better too.
The `isNil` function was implemented and I used it, but it was unnecessary... 😂

Thanks for your help. 🙇‍♂️
